package com.yaya.product.model;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

public class ProductPriceHistory implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_price_history.PRODUCT_PRICE_HISTORY_ID
     *
     * @mbggenerated
     */
    private String productPriceHistoryId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_price_history.MERCHANT_ID
     *
     * @mbggenerated
     */
    private String merchantId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_price_history.MERCHANT_NAME
     *
     * @mbggenerated
     */
    private String merchantName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_price_history.PRODUCT_ID
     *
     * @mbggenerated
     */
    private String productId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_price_history.PRODUCT_NAME
     *
     * @mbggenerated
     */
    private String productName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_price_history.PRODUCT_PRICE
     *
     * @mbggenerated
     */
    private BigDecimal productPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_price_history.CREATE_TIME
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table product_price_history
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_price_history.PRODUCT_PRICE_HISTORY_ID
     *
     * @return the value of product_price_history.PRODUCT_PRICE_HISTORY_ID
     *
     * @mbggenerated
     */
    public String getProductPriceHistoryId() {
        return productPriceHistoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_price_history.PRODUCT_PRICE_HISTORY_ID
     *
     * @param productPriceHistoryId the value for product_price_history.PRODUCT_PRICE_HISTORY_ID
     *
     * @mbggenerated
     */
    public void setProductPriceHistoryId(String productPriceHistoryId) {
        this.productPriceHistoryId = productPriceHistoryId == null ? null : productPriceHistoryId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_price_history.MERCHANT_ID
     *
     * @return the value of product_price_history.MERCHANT_ID
     *
     * @mbggenerated
     */
    public String getMerchantId() {
        return merchantId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_price_history.MERCHANT_ID
     *
     * @param merchantId the value for product_price_history.MERCHANT_ID
     *
     * @mbggenerated
     */
    public void setMerchantId(String merchantId) {
        this.merchantId = merchantId == null ? null : merchantId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_price_history.MERCHANT_NAME
     *
     * @return the value of product_price_history.MERCHANT_NAME
     *
     * @mbggenerated
     */
    public String getMerchantName() {
        return merchantName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_price_history.MERCHANT_NAME
     *
     * @param merchantName the value for product_price_history.MERCHANT_NAME
     *
     * @mbggenerated
     */
    public void setMerchantName(String merchantName) {
        this.merchantName = merchantName == null ? null : merchantName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_price_history.PRODUCT_ID
     *
     * @return the value of product_price_history.PRODUCT_ID
     *
     * @mbggenerated
     */
    public String getProductId() {
        return productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_price_history.PRODUCT_ID
     *
     * @param productId the value for product_price_history.PRODUCT_ID
     *
     * @mbggenerated
     */
    public void setProductId(String productId) {
        this.productId = productId == null ? null : productId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_price_history.PRODUCT_NAME
     *
     * @return the value of product_price_history.PRODUCT_NAME
     *
     * @mbggenerated
     */
    public String getProductName() {
        return productName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_price_history.PRODUCT_NAME
     *
     * @param productName the value for product_price_history.PRODUCT_NAME
     *
     * @mbggenerated
     */
    public void setProductName(String productName) {
        this.productName = productName == null ? null : productName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_price_history.PRODUCT_PRICE
     *
     * @return the value of product_price_history.PRODUCT_PRICE
     *
     * @mbggenerated
     */
    public BigDecimal getProductPrice() {
        return productPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_price_history.PRODUCT_PRICE
     *
     * @param productPrice the value for product_price_history.PRODUCT_PRICE
     *
     * @mbggenerated
     */
    public void setProductPrice(BigDecimal productPrice) {
        this.productPrice = productPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_price_history.CREATE_TIME
     *
     * @return the value of product_price_history.CREATE_TIME
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_price_history.CREATE_TIME
     *
     * @param createTime the value for product_price_history.CREATE_TIME
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_price_history
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", productPriceHistoryId=").append(productPriceHistoryId);
        sb.append(", merchantId=").append(merchantId);
        sb.append(", merchantName=").append(merchantName);
        sb.append(", productId=").append(productId);
        sb.append(", productName=").append(productName);
        sb.append(", productPrice=").append(productPrice);
        sb.append(", createTime=").append(createTime);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}