package com.yaya.product.model;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

public class Product implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.PRODUCT_ID
     *
     * @mbggenerated
     */
    private String productId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.PRODUCT_NAME
     *
     * @mbggenerated
     */
    private String productName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.PRODUCT_DESCRIPTION
     *
     * @mbggenerated
     */
    private String productDescription;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.PRODUCT_PRICE
     *
     * @mbggenerated
     */
    private BigDecimal productPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.PRODUCT_PICTURE
     *
     * @mbggenerated
     */
    private String productPicture;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.PRODUCT_ORDER_COUNT
     *
     * @mbggenerated
     */
    private Integer productOrderCount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.PRODUCT_ENABLE
     *
     * @mbggenerated
     */
    private String productEnable;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.CREATE_TIME
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.LAST_UPDATE_TIME
     *
     * @mbggenerated
     */
    private Date lastUpdateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.MERCHANT_ID
     *
     * @mbggenerated
     */
    private String merchantId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table product
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.PRODUCT_ID
     *
     * @return the value of product.PRODUCT_ID
     *
     * @mbggenerated
     */
    public String getProductId() {
        return productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.PRODUCT_ID
     *
     * @param productId the value for product.PRODUCT_ID
     *
     * @mbggenerated
     */
    public void setProductId(String productId) {
        this.productId = productId == null ? null : productId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.PRODUCT_NAME
     *
     * @return the value of product.PRODUCT_NAME
     *
     * @mbggenerated
     */
    public String getProductName() {
        return productName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.PRODUCT_NAME
     *
     * @param productName the value for product.PRODUCT_NAME
     *
     * @mbggenerated
     */
    public void setProductName(String productName) {
        this.productName = productName == null ? null : productName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.PRODUCT_DESCRIPTION
     *
     * @return the value of product.PRODUCT_DESCRIPTION
     *
     * @mbggenerated
     */
    public String getProductDescription() {
        return productDescription;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.PRODUCT_DESCRIPTION
     *
     * @param productDescription the value for product.PRODUCT_DESCRIPTION
     *
     * @mbggenerated
     */
    public void setProductDescription(String productDescription) {
        this.productDescription = productDescription == null ? null : productDescription.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.PRODUCT_PRICE
     *
     * @return the value of product.PRODUCT_PRICE
     *
     * @mbggenerated
     */
    public BigDecimal getProductPrice() {
        return productPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.PRODUCT_PRICE
     *
     * @param productPrice the value for product.PRODUCT_PRICE
     *
     * @mbggenerated
     */
    public void setProductPrice(BigDecimal productPrice) {
        this.productPrice = productPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.PRODUCT_PICTURE
     *
     * @return the value of product.PRODUCT_PICTURE
     *
     * @mbggenerated
     */
    public String getProductPicture() {
        return productPicture;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.PRODUCT_PICTURE
     *
     * @param productPicture the value for product.PRODUCT_PICTURE
     *
     * @mbggenerated
     */
    public void setProductPicture(String productPicture) {
        this.productPicture = productPicture == null ? null : productPicture.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.PRODUCT_ORDER_COUNT
     *
     * @return the value of product.PRODUCT_ORDER_COUNT
     *
     * @mbggenerated
     */
    public Integer getProductOrderCount() {
        return productOrderCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.PRODUCT_ORDER_COUNT
     *
     * @param productOrderCount the value for product.PRODUCT_ORDER_COUNT
     *
     * @mbggenerated
     */
    public void setProductOrderCount(Integer productOrderCount) {
        this.productOrderCount = productOrderCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.PRODUCT_ENABLE
     *
     * @return the value of product.PRODUCT_ENABLE
     *
     * @mbggenerated
     */
    public String getProductEnable() {
        return productEnable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.PRODUCT_ENABLE
     *
     * @param productEnable the value for product.PRODUCT_ENABLE
     *
     * @mbggenerated
     */
    public void setProductEnable(String productEnable) {
        this.productEnable = productEnable == null ? null : productEnable.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.CREATE_TIME
     *
     * @return the value of product.CREATE_TIME
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.CREATE_TIME
     *
     * @param createTime the value for product.CREATE_TIME
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.LAST_UPDATE_TIME
     *
     * @return the value of product.LAST_UPDATE_TIME
     *
     * @mbggenerated
     */
    public Date getLastUpdateTime() {
        return lastUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.LAST_UPDATE_TIME
     *
     * @param lastUpdateTime the value for product.LAST_UPDATE_TIME
     *
     * @mbggenerated
     */
    public void setLastUpdateTime(Date lastUpdateTime) {
        this.lastUpdateTime = lastUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.MERCHANT_ID
     *
     * @return the value of product.MERCHANT_ID
     *
     * @mbggenerated
     */
    public String getMerchantId() {
        return merchantId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.MERCHANT_ID
     *
     * @param merchantId the value for product.MERCHANT_ID
     *
     * @mbggenerated
     */
    public void setMerchantId(String merchantId) {
        this.merchantId = merchantId == null ? null : merchantId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", productId=").append(productId);
        sb.append(", productName=").append(productName);
        sb.append(", productDescription=").append(productDescription);
        sb.append(", productPrice=").append(productPrice);
        sb.append(", productPicture=").append(productPicture);
        sb.append(", productOrderCount=").append(productOrderCount);
        sb.append(", productEnable=").append(productEnable);
        sb.append(", createTime=").append(createTime);
        sb.append(", lastUpdateTime=").append(lastUpdateTime);
        sb.append(", merchantId=").append(merchantId);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}