package com.yaya.order.model;

import java.io.Serializable;
import java.util.Date;

public class DeliveryOrder implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column delivery_order.DELIVERY_ORDER_ID
     *
     * @mbggenerated
     */
    private String deliveryOrderId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column delivery_order.DELIVERY_ID
     *
     * @mbggenerated
     */
    private String deliveryId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column delivery_order.ORDER_ID
     *
     * @mbggenerated
     */
    private String orderId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column delivery_order.CREATE_TIME
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table delivery_order
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column delivery_order.DELIVERY_ORDER_ID
     *
     * @return the value of delivery_order.DELIVERY_ORDER_ID
     *
     * @mbggenerated
     */
    public String getDeliveryOrderId() {
        return deliveryOrderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column delivery_order.DELIVERY_ORDER_ID
     *
     * @param deliveryOrderId the value for delivery_order.DELIVERY_ORDER_ID
     *
     * @mbggenerated
     */
    public void setDeliveryOrderId(String deliveryOrderId) {
        this.deliveryOrderId = deliveryOrderId == null ? null : deliveryOrderId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column delivery_order.DELIVERY_ID
     *
     * @return the value of delivery_order.DELIVERY_ID
     *
     * @mbggenerated
     */
    public String getDeliveryId() {
        return deliveryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column delivery_order.DELIVERY_ID
     *
     * @param deliveryId the value for delivery_order.DELIVERY_ID
     *
     * @mbggenerated
     */
    public void setDeliveryId(String deliveryId) {
        this.deliveryId = deliveryId == null ? null : deliveryId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column delivery_order.ORDER_ID
     *
     * @return the value of delivery_order.ORDER_ID
     *
     * @mbggenerated
     */
    public String getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column delivery_order.ORDER_ID
     *
     * @param orderId the value for delivery_order.ORDER_ID
     *
     * @mbggenerated
     */
    public void setOrderId(String orderId) {
        this.orderId = orderId == null ? null : orderId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column delivery_order.CREATE_TIME
     *
     * @return the value of delivery_order.CREATE_TIME
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column delivery_order.CREATE_TIME
     *
     * @param createTime the value for delivery_order.CREATE_TIME
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table delivery_order
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", deliveryOrderId=").append(deliveryOrderId);
        sb.append(", deliveryId=").append(deliveryId);
        sb.append(", orderId=").append(orderId);
        sb.append(", createTime=").append(createTime);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}