package com.yaya.order.model;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

public class Orders implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.ORDER_ID
     *
     * @mbg.generated
     */
    private String orderId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.CLIENT_ID
     *
     * @mbg.generated
     */
    private String clientId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.MERCHANT_ID
     *
     * @mbg.generated
     */
    private String merchantId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.ORDER_STATUS
     *
     * @mbg.generated
     */
    private String orderStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.ORDER_TOTAL_AMOUNT
     *
     * @mbg.generated
     */
    private BigDecimal orderTotalAmount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.ORDER_DESC
     *
     * @mbg.generated
     */
    private String orderDesc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.CREATE_TIME
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table orders
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.ORDER_ID
     *
     * @return the value of orders.ORDER_ID
     *
     * @mbg.generated
     */
    public String getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.ORDER_ID
     *
     * @param orderId the value for orders.ORDER_ID
     *
     * @mbg.generated
     */
    public void setOrderId(String orderId) {
        this.orderId = orderId == null ? null : orderId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.CLIENT_ID
     *
     * @return the value of orders.CLIENT_ID
     *
     * @mbg.generated
     */
    public String getClientId() {
        return clientId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.CLIENT_ID
     *
     * @param clientId the value for orders.CLIENT_ID
     *
     * @mbg.generated
     */
    public void setClientId(String clientId) {
        this.clientId = clientId == null ? null : clientId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.MERCHANT_ID
     *
     * @return the value of orders.MERCHANT_ID
     *
     * @mbg.generated
     */
    public String getMerchantId() {
        return merchantId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.MERCHANT_ID
     *
     * @param merchantId the value for orders.MERCHANT_ID
     *
     * @mbg.generated
     */
    public void setMerchantId(String merchantId) {
        this.merchantId = merchantId == null ? null : merchantId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.ORDER_STATUS
     *
     * @return the value of orders.ORDER_STATUS
     *
     * @mbg.generated
     */
    public String getOrderStatus() {
        return orderStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.ORDER_STATUS
     *
     * @param orderStatus the value for orders.ORDER_STATUS
     *
     * @mbg.generated
     */
    public void setOrderStatus(String orderStatus) {
        this.orderStatus = orderStatus == null ? null : orderStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.ORDER_TOTAL_AMOUNT
     *
     * @return the value of orders.ORDER_TOTAL_AMOUNT
     *
     * @mbg.generated
     */
    public BigDecimal getOrderTotalAmount() {
        return orderTotalAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.ORDER_TOTAL_AMOUNT
     *
     * @param orderTotalAmount the value for orders.ORDER_TOTAL_AMOUNT
     *
     * @mbg.generated
     */
    public void setOrderTotalAmount(BigDecimal orderTotalAmount) {
        this.orderTotalAmount = orderTotalAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.ORDER_DESC
     *
     * @return the value of orders.ORDER_DESC
     *
     * @mbg.generated
     */
    public String getOrderDesc() {
        return orderDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.ORDER_DESC
     *
     * @param orderDesc the value for orders.ORDER_DESC
     *
     * @mbg.generated
     */
    public void setOrderDesc(String orderDesc) {
        this.orderDesc = orderDesc == null ? null : orderDesc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.CREATE_TIME
     *
     * @return the value of orders.CREATE_TIME
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.CREATE_TIME
     *
     * @param createTime the value for orders.CREATE_TIME
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orders
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", orderId=").append(orderId);
        sb.append(", clientId=").append(clientId);
        sb.append(", merchantId=").append(merchantId);
        sb.append(", orderStatus=").append(orderStatus);
        sb.append(", orderTotalAmount=").append(orderTotalAmount);
        sb.append(", orderDesc=").append(orderDesc);
        sb.append(", createTime=").append(createTime);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}