#服务端口
server:
  port: 8093

#配置服务注册中心服务器地址
eureka:
  client:
    service-url:
      defaultZone:  http://localhost:8010/eureka/


#服务名称
spring:
  application:
    name: gateway_server
  cloud:
    gateway:
      discovery:
        locator:
          #是否与服务发现组件进行结合，通过 serviceId 转发到具体的服务实例。
          # 默认为false，设为true便开启通过服务中心的自动根据 serviceId 创建路由的功能
          enabled:  true
      routes:
        - id: merchant
          uri:  lb://MERCHANT
          predicates:
            - Path=/merchant/**
        - id: configServer
          uri:  http://localhost:8091
          predicates:
            - Path=/config/**
        - id: 163                     #网关路由到baidu
          uri: http://www.baidu.com/
          predicates:
            - Path=/b/**