#服务端口
server:
  port: 8093

#配置服务注册中心服务器地址
eureka:
  client:
    service-url:
      defaultZone:  http://localhost:8010/eureka/


#服务名称
spring:
  application:
    name: gateway_server
  cloud:
    gateway:
      discovery:
        locator:
          #是否与服务发现组件进行结合，通过 serviceId 转发到具体的服务实例。
          # 默认为false，设为true便开启通过服务中心的自动根据 serviceId 创建路由的功能
          enabled:  true
      routes:
        - id: merchant
          #采用注册中心的注册名字的方式
          uri:  lb://MERCHANT
          predicates:
            - Path=/merchant/**
          #采用ip地址+端口方式
        - id: configServer
          uri:  http://localhost:8091
          predicates:
            - Path=/config/**
        - id: permission
          uri: http://localhost:8089
          predicates:
            - Path=/permission/**
          filters:
            - name: Hystrix
              args:
                name: getMethodNameByType
                fallbackUri: forward:http://localhost:8089/permission/getMethodNameByTypeHystrix