package com.yaya.orderApi.discountModel;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

public class MerchantAllProductDiscountRateHistory implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column merchant_all_product_discount_rate_history.ALL_PRODUCT_DISCOUNT_RATE_ID
     *
     * @mbggenerated
     */
    private String allProductDiscountRateId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column merchant_all_product_discount_rate_history.MERCHANT_ID
     *
     * @mbggenerated
     */
    private String merchantId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column merchant_all_product_discount_rate_history.ALL_PRODUCT_DISCOUNT_RATE
     *
     * @mbggenerated
     */
    private BigDecimal allProductDiscountRate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column merchant_all_product_discount_rate_history.DISCOUNT_DESC
     *
     * @mbggenerated
     */
    private String discountDesc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column merchant_all_product_discount_rate_history.CREATE_DATE
     *
     * @mbggenerated
     */
    private Date createDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table merchant_all_product_discount_rate_history
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column merchant_all_product_discount_rate_history.ALL_PRODUCT_DISCOUNT_RATE_ID
     *
     * @return the value of merchant_all_product_discount_rate_history.ALL_PRODUCT_DISCOUNT_RATE_ID
     *
     * @mbggenerated
     */
    public String getAllProductDiscountRateId() {
        return allProductDiscountRateId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column merchant_all_product_discount_rate_history.ALL_PRODUCT_DISCOUNT_RATE_ID
     *
     * @param allProductDiscountRateId the value for merchant_all_product_discount_rate_history.ALL_PRODUCT_DISCOUNT_RATE_ID
     *
     * @mbggenerated
     */
    public void setAllProductDiscountRateId(String allProductDiscountRateId) {
        this.allProductDiscountRateId = allProductDiscountRateId == null ? null : allProductDiscountRateId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column merchant_all_product_discount_rate_history.MERCHANT_ID
     *
     * @return the value of merchant_all_product_discount_rate_history.MERCHANT_ID
     *
     * @mbggenerated
     */
    public String getMerchantId() {
        return merchantId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column merchant_all_product_discount_rate_history.MERCHANT_ID
     *
     * @param merchantId the value for merchant_all_product_discount_rate_history.MERCHANT_ID
     *
     * @mbggenerated
     */
    public void setMerchantId(String merchantId) {
        this.merchantId = merchantId == null ? null : merchantId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column merchant_all_product_discount_rate_history.ALL_PRODUCT_DISCOUNT_RATE
     *
     * @return the value of merchant_all_product_discount_rate_history.ALL_PRODUCT_DISCOUNT_RATE
     *
     * @mbggenerated
     */
    public BigDecimal getAllProductDiscountRate() {
        return allProductDiscountRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column merchant_all_product_discount_rate_history.ALL_PRODUCT_DISCOUNT_RATE
     *
     * @param allProductDiscountRate the value for merchant_all_product_discount_rate_history.ALL_PRODUCT_DISCOUNT_RATE
     *
     * @mbggenerated
     */
    public void setAllProductDiscountRate(BigDecimal allProductDiscountRate) {
        this.allProductDiscountRate = allProductDiscountRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column merchant_all_product_discount_rate_history.DISCOUNT_DESC
     *
     * @return the value of merchant_all_product_discount_rate_history.DISCOUNT_DESC
     *
     * @mbggenerated
     */
    public String getDiscountDesc() {
        return discountDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column merchant_all_product_discount_rate_history.DISCOUNT_DESC
     *
     * @param discountDesc the value for merchant_all_product_discount_rate_history.DISCOUNT_DESC
     *
     * @mbggenerated
     */
    public void setDiscountDesc(String discountDesc) {
        this.discountDesc = discountDesc == null ? null : discountDesc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column merchant_all_product_discount_rate_history.CREATE_DATE
     *
     * @return the value of merchant_all_product_discount_rate_history.CREATE_DATE
     *
     * @mbggenerated
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column merchant_all_product_discount_rate_history.CREATE_DATE
     *
     * @param createDate the value for merchant_all_product_discount_rate_history.CREATE_DATE
     *
     * @mbggenerated
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table merchant_all_product_discount_rate_history
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", allProductDiscountRateId=").append(allProductDiscountRateId);
        sb.append(", merchantId=").append(merchantId);
        sb.append(", allProductDiscountRate=").append(allProductDiscountRate);
        sb.append(", discountDesc=").append(discountDesc);
        sb.append(", createDate=").append(createDate);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}