package com.yaya.orderApi.discountModel;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

public class MerchantSignalProductDiscountPriceHistory implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column merchant_signal_product_discount_price_history.PRODUCT_DISCOUNT_PRICE_ID
     *
     * @mbggenerated
     */
    private String productDiscountPriceId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column merchant_signal_product_discount_price_history.MERCHANT_ID
     *
     * @mbggenerated
     */
    private String merchantId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column merchant_signal_product_discount_price_history.PRODUCT_ID
     *
     * @mbggenerated
     */
    private String productId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column merchant_signal_product_discount_price_history.DISCOUNT_PRICE
     *
     * @mbggenerated
     */
    private BigDecimal discountPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column merchant_signal_product_discount_price_history.CREATE_TIME
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table merchant_signal_product_discount_price_history
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column merchant_signal_product_discount_price_history.PRODUCT_DISCOUNT_PRICE_ID
     *
     * @return the value of merchant_signal_product_discount_price_history.PRODUCT_DISCOUNT_PRICE_ID
     *
     * @mbggenerated
     */
    public String getProductDiscountPriceId() {
        return productDiscountPriceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column merchant_signal_product_discount_price_history.PRODUCT_DISCOUNT_PRICE_ID
     *
     * @param productDiscountPriceId the value for merchant_signal_product_discount_price_history.PRODUCT_DISCOUNT_PRICE_ID
     *
     * @mbggenerated
     */
    public void setProductDiscountPriceId(String productDiscountPriceId) {
        this.productDiscountPriceId = productDiscountPriceId == null ? null : productDiscountPriceId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column merchant_signal_product_discount_price_history.MERCHANT_ID
     *
     * @return the value of merchant_signal_product_discount_price_history.MERCHANT_ID
     *
     * @mbggenerated
     */
    public String getMerchantId() {
        return merchantId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column merchant_signal_product_discount_price_history.MERCHANT_ID
     *
     * @param merchantId the value for merchant_signal_product_discount_price_history.MERCHANT_ID
     *
     * @mbggenerated
     */
    public void setMerchantId(String merchantId) {
        this.merchantId = merchantId == null ? null : merchantId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column merchant_signal_product_discount_price_history.PRODUCT_ID
     *
     * @return the value of merchant_signal_product_discount_price_history.PRODUCT_ID
     *
     * @mbggenerated
     */
    public String getProductId() {
        return productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column merchant_signal_product_discount_price_history.PRODUCT_ID
     *
     * @param productId the value for merchant_signal_product_discount_price_history.PRODUCT_ID
     *
     * @mbggenerated
     */
    public void setProductId(String productId) {
        this.productId = productId == null ? null : productId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column merchant_signal_product_discount_price_history.DISCOUNT_PRICE
     *
     * @return the value of merchant_signal_product_discount_price_history.DISCOUNT_PRICE
     *
     * @mbggenerated
     */
    public BigDecimal getDiscountPrice() {
        return discountPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column merchant_signal_product_discount_price_history.DISCOUNT_PRICE
     *
     * @param discountPrice the value for merchant_signal_product_discount_price_history.DISCOUNT_PRICE
     *
     * @mbggenerated
     */
    public void setDiscountPrice(BigDecimal discountPrice) {
        this.discountPrice = discountPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column merchant_signal_product_discount_price_history.CREATE_TIME
     *
     * @return the value of merchant_signal_product_discount_price_history.CREATE_TIME
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column merchant_signal_product_discount_price_history.CREATE_TIME
     *
     * @param createTime the value for merchant_signal_product_discount_price_history.CREATE_TIME
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table merchant_signal_product_discount_price_history
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", productDiscountPriceId=").append(productDiscountPriceId);
        sb.append(", merchantId=").append(merchantId);
        sb.append(", productId=").append(productId);
        sb.append(", discountPrice=").append(discountPrice);
        sb.append(", createTime=").append(createTime);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}