package com.yaya.orderApi.discountModel;

import java.io.Serializable;
import java.util.Date;

public class MerchantPublicDiscountHistory implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column merchant_public_discount_history.MERCHANT_PUBLIC_ID
     *
     * @mbggenerated
     */
    private String merchantPublicId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column merchant_public_discount_history.MERCHANT_ID
     *
     * @mbggenerated
     */
    private String merchantId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column merchant_public_discount_history.PUBLIC_DISCOUNT_ID
     *
     * @mbggenerated
     */
    private String publicDiscountId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column merchant_public_discount_history.CREATE_TIME
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table merchant_public_discount_history
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column merchant_public_discount_history.MERCHANT_PUBLIC_ID
     *
     * @return the value of merchant_public_discount_history.MERCHANT_PUBLIC_ID
     *
     * @mbggenerated
     */
    public String getMerchantPublicId() {
        return merchantPublicId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column merchant_public_discount_history.MERCHANT_PUBLIC_ID
     *
     * @param merchantPublicId the value for merchant_public_discount_history.MERCHANT_PUBLIC_ID
     *
     * @mbggenerated
     */
    public void setMerchantPublicId(String merchantPublicId) {
        this.merchantPublicId = merchantPublicId == null ? null : merchantPublicId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column merchant_public_discount_history.MERCHANT_ID
     *
     * @return the value of merchant_public_discount_history.MERCHANT_ID
     *
     * @mbggenerated
     */
    public String getMerchantId() {
        return merchantId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column merchant_public_discount_history.MERCHANT_ID
     *
     * @param merchantId the value for merchant_public_discount_history.MERCHANT_ID
     *
     * @mbggenerated
     */
    public void setMerchantId(String merchantId) {
        this.merchantId = merchantId == null ? null : merchantId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column merchant_public_discount_history.PUBLIC_DISCOUNT_ID
     *
     * @return the value of merchant_public_discount_history.PUBLIC_DISCOUNT_ID
     *
     * @mbggenerated
     */
    public String getPublicDiscountId() {
        return publicDiscountId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column merchant_public_discount_history.PUBLIC_DISCOUNT_ID
     *
     * @param publicDiscountId the value for merchant_public_discount_history.PUBLIC_DISCOUNT_ID
     *
     * @mbggenerated
     */
    public void setPublicDiscountId(String publicDiscountId) {
        this.publicDiscountId = publicDiscountId == null ? null : publicDiscountId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column merchant_public_discount_history.CREATE_TIME
     *
     * @return the value of merchant_public_discount_history.CREATE_TIME
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column merchant_public_discount_history.CREATE_TIME
     *
     * @param createTime the value for merchant_public_discount_history.CREATE_TIME
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table merchant_public_discount_history
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", merchantPublicId=").append(merchantPublicId);
        sb.append(", merchantId=").append(merchantId);
        sb.append(", publicDiscountId=").append(publicDiscountId);
        sb.append(", createTime=").append(createTime);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}