package com.yaya.orderapi.discountModel;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

public class MerchantSignalProductDiscountPrice implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column merchant_signal_product_discount_price.PRODUCT_DISCOUNT_PRICE_ID
     *
     * @mbggenerated
     */
    private String productDiscountPriceId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column merchant_signal_product_discount_price.MERCHANT_ID
     *
     * @mbggenerated
     */
    private String merchantId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column merchant_signal_product_discount_price.PRODUCT_ID
     *
     * @mbggenerated
     */
    private String productId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column merchant_signal_product_discount_price.DISCOUNT_PRICE
     *
     * @mbggenerated
     */
    private BigDecimal discountPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column merchant_signal_product_discount_price.DISCOUNT_DESC
     *
     * @mbggenerated
     */
    private String discountDesc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column merchant_signal_product_discount_price.LAST_UPDATE_TIME
     *
     * @mbggenerated
     */
    private Date lastUpdateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table merchant_signal_product_discount_price
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column merchant_signal_product_discount_price.PRODUCT_DISCOUNT_PRICE_ID
     *
     * @return the value of merchant_signal_product_discount_price.PRODUCT_DISCOUNT_PRICE_ID
     *
     * @mbggenerated
     */
    public String getProductDiscountPriceId() {
        return productDiscountPriceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column merchant_signal_product_discount_price.PRODUCT_DISCOUNT_PRICE_ID
     *
     * @param productDiscountPriceId the value for merchant_signal_product_discount_price.PRODUCT_DISCOUNT_PRICE_ID
     *
     * @mbggenerated
     */
    public void setProductDiscountPriceId(String productDiscountPriceId) {
        this.productDiscountPriceId = productDiscountPriceId == null ? null : productDiscountPriceId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column merchant_signal_product_discount_price.MERCHANT_ID
     *
     * @return the value of merchant_signal_product_discount_price.MERCHANT_ID
     *
     * @mbggenerated
     */
    public String getMerchantId() {
        return merchantId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column merchant_signal_product_discount_price.MERCHANT_ID
     *
     * @param merchantId the value for merchant_signal_product_discount_price.MERCHANT_ID
     *
     * @mbggenerated
     */
    public void setMerchantId(String merchantId) {
        this.merchantId = merchantId == null ? null : merchantId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column merchant_signal_product_discount_price.PRODUCT_ID
     *
     * @return the value of merchant_signal_product_discount_price.PRODUCT_ID
     *
     * @mbggenerated
     */
    public String getProductId() {
        return productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column merchant_signal_product_discount_price.PRODUCT_ID
     *
     * @param productId the value for merchant_signal_product_discount_price.PRODUCT_ID
     *
     * @mbggenerated
     */
    public void setProductId(String productId) {
        this.productId = productId == null ? null : productId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column merchant_signal_product_discount_price.DISCOUNT_PRICE
     *
     * @return the value of merchant_signal_product_discount_price.DISCOUNT_PRICE
     *
     * @mbggenerated
     */
    public BigDecimal getDiscountPrice() {
        return discountPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column merchant_signal_product_discount_price.DISCOUNT_PRICE
     *
     * @param discountPrice the value for merchant_signal_product_discount_price.DISCOUNT_PRICE
     *
     * @mbggenerated
     */
    public void setDiscountPrice(BigDecimal discountPrice) {
        this.discountPrice = discountPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column merchant_signal_product_discount_price.DISCOUNT_DESC
     *
     * @return the value of merchant_signal_product_discount_price.DISCOUNT_DESC
     *
     * @mbggenerated
     */
    public String getDiscountDesc() {
        return discountDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column merchant_signal_product_discount_price.DISCOUNT_DESC
     *
     * @param discountDesc the value for merchant_signal_product_discount_price.DISCOUNT_DESC
     *
     * @mbggenerated
     */
    public void setDiscountDesc(String discountDesc) {
        this.discountDesc = discountDesc == null ? null : discountDesc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column merchant_signal_product_discount_price.LAST_UPDATE_TIME
     *
     * @return the value of merchant_signal_product_discount_price.LAST_UPDATE_TIME
     *
     * @mbggenerated
     */
    public Date getLastUpdateTime() {
        return lastUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column merchant_signal_product_discount_price.LAST_UPDATE_TIME
     *
     * @param lastUpdateTime the value for merchant_signal_product_discount_price.LAST_UPDATE_TIME
     *
     * @mbggenerated
     */
    public void setLastUpdateTime(Date lastUpdateTime) {
        this.lastUpdateTime = lastUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table merchant_signal_product_discount_price
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", productDiscountPriceId=").append(productDiscountPriceId);
        sb.append(", merchantId=").append(merchantId);
        sb.append(", productId=").append(productId);
        sb.append(", discountPrice=").append(discountPrice);
        sb.append(", discountDesc=").append(discountDesc);
        sb.append(", lastUpdateTime=").append(lastUpdateTime);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}