package com.yaya.orderapi.discountModel;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

public class OtherPublicDiscount implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column other_public_discount.PUBLIC_DISCOUNT_ID
     *
     * @mbggenerated
     */
    private String publicDiscountId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column other_public_discount.DISCOUNT_AMOUNT
     *
     * @mbggenerated
     */
    private BigDecimal discountAmount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column other_public_discount.DISCOUNT_DESC
     *
     * @mbggenerated
     */
    private String discountDesc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column other_public_discount.DISCOUNT_BEGIN_DATE
     *
     * @mbggenerated
     */
    private Date discountBeginDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column other_public_discount.DISCOUNT_END_DATE
     *
     * @mbggenerated
     */
    private Date discountEndDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column other_public_discount.DISCOUNT_STATUS
     *
     * @mbggenerated
     */
    private String discountStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column other_public_discount.LAST_UPDATE_TIME
     *
     * @mbggenerated
     */
    private Date lastUpdateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table other_public_discount
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column other_public_discount.PUBLIC_DISCOUNT_ID
     *
     * @return the value of other_public_discount.PUBLIC_DISCOUNT_ID
     *
     * @mbggenerated
     */
    public String getPublicDiscountId() {
        return publicDiscountId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column other_public_discount.PUBLIC_DISCOUNT_ID
     *
     * @param publicDiscountId the value for other_public_discount.PUBLIC_DISCOUNT_ID
     *
     * @mbggenerated
     */
    public void setPublicDiscountId(String publicDiscountId) {
        this.publicDiscountId = publicDiscountId == null ? null : publicDiscountId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column other_public_discount.DISCOUNT_AMOUNT
     *
     * @return the value of other_public_discount.DISCOUNT_AMOUNT
     *
     * @mbggenerated
     */
    public BigDecimal getDiscountAmount() {
        return discountAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column other_public_discount.DISCOUNT_AMOUNT
     *
     * @param discountAmount the value for other_public_discount.DISCOUNT_AMOUNT
     *
     * @mbggenerated
     */
    public void setDiscountAmount(BigDecimal discountAmount) {
        this.discountAmount = discountAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column other_public_discount.DISCOUNT_DESC
     *
     * @return the value of other_public_discount.DISCOUNT_DESC
     *
     * @mbggenerated
     */
    public String getDiscountDesc() {
        return discountDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column other_public_discount.DISCOUNT_DESC
     *
     * @param discountDesc the value for other_public_discount.DISCOUNT_DESC
     *
     * @mbggenerated
     */
    public void setDiscountDesc(String discountDesc) {
        this.discountDesc = discountDesc == null ? null : discountDesc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column other_public_discount.DISCOUNT_BEGIN_DATE
     *
     * @return the value of other_public_discount.DISCOUNT_BEGIN_DATE
     *
     * @mbggenerated
     */
    public Date getDiscountBeginDate() {
        return discountBeginDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column other_public_discount.DISCOUNT_BEGIN_DATE
     *
     * @param discountBeginDate the value for other_public_discount.DISCOUNT_BEGIN_DATE
     *
     * @mbggenerated
     */
    public void setDiscountBeginDate(Date discountBeginDate) {
        this.discountBeginDate = discountBeginDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column other_public_discount.DISCOUNT_END_DATE
     *
     * @return the value of other_public_discount.DISCOUNT_END_DATE
     *
     * @mbggenerated
     */
    public Date getDiscountEndDate() {
        return discountEndDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column other_public_discount.DISCOUNT_END_DATE
     *
     * @param discountEndDate the value for other_public_discount.DISCOUNT_END_DATE
     *
     * @mbggenerated
     */
    public void setDiscountEndDate(Date discountEndDate) {
        this.discountEndDate = discountEndDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column other_public_discount.DISCOUNT_STATUS
     *
     * @return the value of other_public_discount.DISCOUNT_STATUS
     *
     * @mbggenerated
     */
    public String getDiscountStatus() {
        return discountStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column other_public_discount.DISCOUNT_STATUS
     *
     * @param discountStatus the value for other_public_discount.DISCOUNT_STATUS
     *
     * @mbggenerated
     */
    public void setDiscountStatus(String discountStatus) {
        this.discountStatus = discountStatus == null ? null : discountStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column other_public_discount.LAST_UPDATE_TIME
     *
     * @return the value of other_public_discount.LAST_UPDATE_TIME
     *
     * @mbggenerated
     */
    public Date getLastUpdateTime() {
        return lastUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column other_public_discount.LAST_UPDATE_TIME
     *
     * @param lastUpdateTime the value for other_public_discount.LAST_UPDATE_TIME
     *
     * @mbggenerated
     */
    public void setLastUpdateTime(Date lastUpdateTime) {
        this.lastUpdateTime = lastUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table other_public_discount
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", publicDiscountId=").append(publicDiscountId);
        sb.append(", discountAmount=").append(discountAmount);
        sb.append(", discountDesc=").append(discountDesc);
        sb.append(", discountBeginDate=").append(discountBeginDate);
        sb.append(", discountEndDate=").append(discountEndDate);
        sb.append(", discountStatus=").append(discountStatus);
        sb.append(", lastUpdateTime=").append(lastUpdateTime);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}