package com.yaya.orderSystem.delivery.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class DeliveryExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table delivery
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table delivery
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table delivery
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table delivery
     *
     * @mbg.generated
     */
    public DeliveryExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table delivery
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table delivery
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table delivery
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table delivery
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table delivery
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table delivery
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table delivery
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table delivery
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table delivery
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table delivery
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table delivery
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andDeliveryIdIsNull() {
            addCriterion("DELIVERY_ID is null");
            return (Criteria) this;
        }

        public Criteria andDeliveryIdIsNotNull() {
            addCriterion("DELIVERY_ID is not null");
            return (Criteria) this;
        }

        public Criteria andDeliveryIdEqualTo(String value) {
            addCriterion("DELIVERY_ID =", value, "deliveryId");
            return (Criteria) this;
        }

        public Criteria andDeliveryIdNotEqualTo(String value) {
            addCriterion("DELIVERY_ID <>", value, "deliveryId");
            return (Criteria) this;
        }

        public Criteria andDeliveryIdGreaterThan(String value) {
            addCriterion("DELIVERY_ID >", value, "deliveryId");
            return (Criteria) this;
        }

        public Criteria andDeliveryIdGreaterThanOrEqualTo(String value) {
            addCriterion("DELIVERY_ID >=", value, "deliveryId");
            return (Criteria) this;
        }

        public Criteria andDeliveryIdLessThan(String value) {
            addCriterion("DELIVERY_ID <", value, "deliveryId");
            return (Criteria) this;
        }

        public Criteria andDeliveryIdLessThanOrEqualTo(String value) {
            addCriterion("DELIVERY_ID <=", value, "deliveryId");
            return (Criteria) this;
        }

        public Criteria andDeliveryIdLike(String value) {
            addCriterion("DELIVERY_ID like", value, "deliveryId");
            return (Criteria) this;
        }

        public Criteria andDeliveryIdNotLike(String value) {
            addCriterion("DELIVERY_ID not like", value, "deliveryId");
            return (Criteria) this;
        }

        public Criteria andDeliveryIdIn(List<String> values) {
            addCriterion("DELIVERY_ID in", values, "deliveryId");
            return (Criteria) this;
        }

        public Criteria andDeliveryIdNotIn(List<String> values) {
            addCriterion("DELIVERY_ID not in", values, "deliveryId");
            return (Criteria) this;
        }

        public Criteria andDeliveryIdBetween(String value1, String value2) {
            addCriterion("DELIVERY_ID between", value1, value2, "deliveryId");
            return (Criteria) this;
        }

        public Criteria andDeliveryIdNotBetween(String value1, String value2) {
            addCriterion("DELIVERY_ID not between", value1, value2, "deliveryId");
            return (Criteria) this;
        }

        public Criteria andDeliveryLoginNameIsNull() {
            addCriterion("DELIVERY_LOGIN_NAME is null");
            return (Criteria) this;
        }

        public Criteria andDeliveryLoginNameIsNotNull() {
            addCriterion("DELIVERY_LOGIN_NAME is not null");
            return (Criteria) this;
        }

        public Criteria andDeliveryLoginNameEqualTo(String value) {
            addCriterion("DELIVERY_LOGIN_NAME =", value, "deliveryLoginName");
            return (Criteria) this;
        }

        public Criteria andDeliveryLoginNameNotEqualTo(String value) {
            addCriterion("DELIVERY_LOGIN_NAME <>", value, "deliveryLoginName");
            return (Criteria) this;
        }

        public Criteria andDeliveryLoginNameGreaterThan(String value) {
            addCriterion("DELIVERY_LOGIN_NAME >", value, "deliveryLoginName");
            return (Criteria) this;
        }

        public Criteria andDeliveryLoginNameGreaterThanOrEqualTo(String value) {
            addCriterion("DELIVERY_LOGIN_NAME >=", value, "deliveryLoginName");
            return (Criteria) this;
        }

        public Criteria andDeliveryLoginNameLessThan(String value) {
            addCriterion("DELIVERY_LOGIN_NAME <", value, "deliveryLoginName");
            return (Criteria) this;
        }

        public Criteria andDeliveryLoginNameLessThanOrEqualTo(String value) {
            addCriterion("DELIVERY_LOGIN_NAME <=", value, "deliveryLoginName");
            return (Criteria) this;
        }

        public Criteria andDeliveryLoginNameLike(String value) {
            addCriterion("DELIVERY_LOGIN_NAME like", value, "deliveryLoginName");
            return (Criteria) this;
        }

        public Criteria andDeliveryLoginNameNotLike(String value) {
            addCriterion("DELIVERY_LOGIN_NAME not like", value, "deliveryLoginName");
            return (Criteria) this;
        }

        public Criteria andDeliveryLoginNameIn(List<String> values) {
            addCriterion("DELIVERY_LOGIN_NAME in", values, "deliveryLoginName");
            return (Criteria) this;
        }

        public Criteria andDeliveryLoginNameNotIn(List<String> values) {
            addCriterion("DELIVERY_LOGIN_NAME not in", values, "deliveryLoginName");
            return (Criteria) this;
        }

        public Criteria andDeliveryLoginNameBetween(String value1, String value2) {
            addCriterion("DELIVERY_LOGIN_NAME between", value1, value2, "deliveryLoginName");
            return (Criteria) this;
        }

        public Criteria andDeliveryLoginNameNotBetween(String value1, String value2) {
            addCriterion("DELIVERY_LOGIN_NAME not between", value1, value2, "deliveryLoginName");
            return (Criteria) this;
        }

        public Criteria andDeliveryNameIsNull() {
            addCriterion("DELIVERY_NAME is null");
            return (Criteria) this;
        }

        public Criteria andDeliveryNameIsNotNull() {
            addCriterion("DELIVERY_NAME is not null");
            return (Criteria) this;
        }

        public Criteria andDeliveryNameEqualTo(String value) {
            addCriterion("DELIVERY_NAME =", value, "deliveryName");
            return (Criteria) this;
        }

        public Criteria andDeliveryNameNotEqualTo(String value) {
            addCriterion("DELIVERY_NAME <>", value, "deliveryName");
            return (Criteria) this;
        }

        public Criteria andDeliveryNameGreaterThan(String value) {
            addCriterion("DELIVERY_NAME >", value, "deliveryName");
            return (Criteria) this;
        }

        public Criteria andDeliveryNameGreaterThanOrEqualTo(String value) {
            addCriterion("DELIVERY_NAME >=", value, "deliveryName");
            return (Criteria) this;
        }

        public Criteria andDeliveryNameLessThan(String value) {
            addCriterion("DELIVERY_NAME <", value, "deliveryName");
            return (Criteria) this;
        }

        public Criteria andDeliveryNameLessThanOrEqualTo(String value) {
            addCriterion("DELIVERY_NAME <=", value, "deliveryName");
            return (Criteria) this;
        }

        public Criteria andDeliveryNameLike(String value) {
            addCriterion("DELIVERY_NAME like", value, "deliveryName");
            return (Criteria) this;
        }

        public Criteria andDeliveryNameNotLike(String value) {
            addCriterion("DELIVERY_NAME not like", value, "deliveryName");
            return (Criteria) this;
        }

        public Criteria andDeliveryNameIn(List<String> values) {
            addCriterion("DELIVERY_NAME in", values, "deliveryName");
            return (Criteria) this;
        }

        public Criteria andDeliveryNameNotIn(List<String> values) {
            addCriterion("DELIVERY_NAME not in", values, "deliveryName");
            return (Criteria) this;
        }

        public Criteria andDeliveryNameBetween(String value1, String value2) {
            addCriterion("DELIVERY_NAME between", value1, value2, "deliveryName");
            return (Criteria) this;
        }

        public Criteria andDeliveryNameNotBetween(String value1, String value2) {
            addCriterion("DELIVERY_NAME not between", value1, value2, "deliveryName");
            return (Criteria) this;
        }

        public Criteria andDeliveryPasswordIsNull() {
            addCriterion("DELIVERY_PASSWORD is null");
            return (Criteria) this;
        }

        public Criteria andDeliveryPasswordIsNotNull() {
            addCriterion("DELIVERY_PASSWORD is not null");
            return (Criteria) this;
        }

        public Criteria andDeliveryPasswordEqualTo(String value) {
            addCriterion("DELIVERY_PASSWORD =", value, "deliveryPassword");
            return (Criteria) this;
        }

        public Criteria andDeliveryPasswordNotEqualTo(String value) {
            addCriterion("DELIVERY_PASSWORD <>", value, "deliveryPassword");
            return (Criteria) this;
        }

        public Criteria andDeliveryPasswordGreaterThan(String value) {
            addCriterion("DELIVERY_PASSWORD >", value, "deliveryPassword");
            return (Criteria) this;
        }

        public Criteria andDeliveryPasswordGreaterThanOrEqualTo(String value) {
            addCriterion("DELIVERY_PASSWORD >=", value, "deliveryPassword");
            return (Criteria) this;
        }

        public Criteria andDeliveryPasswordLessThan(String value) {
            addCriterion("DELIVERY_PASSWORD <", value, "deliveryPassword");
            return (Criteria) this;
        }

        public Criteria andDeliveryPasswordLessThanOrEqualTo(String value) {
            addCriterion("DELIVERY_PASSWORD <=", value, "deliveryPassword");
            return (Criteria) this;
        }

        public Criteria andDeliveryPasswordLike(String value) {
            addCriterion("DELIVERY_PASSWORD like", value, "deliveryPassword");
            return (Criteria) this;
        }

        public Criteria andDeliveryPasswordNotLike(String value) {
            addCriterion("DELIVERY_PASSWORD not like", value, "deliveryPassword");
            return (Criteria) this;
        }

        public Criteria andDeliveryPasswordIn(List<String> values) {
            addCriterion("DELIVERY_PASSWORD in", values, "deliveryPassword");
            return (Criteria) this;
        }

        public Criteria andDeliveryPasswordNotIn(List<String> values) {
            addCriterion("DELIVERY_PASSWORD not in", values, "deliveryPassword");
            return (Criteria) this;
        }

        public Criteria andDeliveryPasswordBetween(String value1, String value2) {
            addCriterion("DELIVERY_PASSWORD between", value1, value2, "deliveryPassword");
            return (Criteria) this;
        }

        public Criteria andDeliveryPasswordNotBetween(String value1, String value2) {
            addCriterion("DELIVERY_PASSWORD not between", value1, value2, "deliveryPassword");
            return (Criteria) this;
        }

        public Criteria andSaltIsNull() {
            addCriterion("SALT is null");
            return (Criteria) this;
        }

        public Criteria andSaltIsNotNull() {
            addCriterion("SALT is not null");
            return (Criteria) this;
        }

        public Criteria andSaltEqualTo(String value) {
            addCriterion("SALT =", value, "salt");
            return (Criteria) this;
        }

        public Criteria andSaltNotEqualTo(String value) {
            addCriterion("SALT <>", value, "salt");
            return (Criteria) this;
        }

        public Criteria andSaltGreaterThan(String value) {
            addCriterion("SALT >", value, "salt");
            return (Criteria) this;
        }

        public Criteria andSaltGreaterThanOrEqualTo(String value) {
            addCriterion("SALT >=", value, "salt");
            return (Criteria) this;
        }

        public Criteria andSaltLessThan(String value) {
            addCriterion("SALT <", value, "salt");
            return (Criteria) this;
        }

        public Criteria andSaltLessThanOrEqualTo(String value) {
            addCriterion("SALT <=", value, "salt");
            return (Criteria) this;
        }

        public Criteria andSaltLike(String value) {
            addCriterion("SALT like", value, "salt");
            return (Criteria) this;
        }

        public Criteria andSaltNotLike(String value) {
            addCriterion("SALT not like", value, "salt");
            return (Criteria) this;
        }

        public Criteria andSaltIn(List<String> values) {
            addCriterion("SALT in", values, "salt");
            return (Criteria) this;
        }

        public Criteria andSaltNotIn(List<String> values) {
            addCriterion("SALT not in", values, "salt");
            return (Criteria) this;
        }

        public Criteria andSaltBetween(String value1, String value2) {
            addCriterion("SALT between", value1, value2, "salt");
            return (Criteria) this;
        }

        public Criteria andSaltNotBetween(String value1, String value2) {
            addCriterion("SALT not between", value1, value2, "salt");
            return (Criteria) this;
        }

        public Criteria andUserTypeIsNull() {
            addCriterion("USER_TYPE is null");
            return (Criteria) this;
        }

        public Criteria andUserTypeIsNotNull() {
            addCriterion("USER_TYPE is not null");
            return (Criteria) this;
        }

        public Criteria andUserTypeEqualTo(String value) {
            addCriterion("USER_TYPE =", value, "userType");
            return (Criteria) this;
        }

        public Criteria andUserTypeNotEqualTo(String value) {
            addCriterion("USER_TYPE <>", value, "userType");
            return (Criteria) this;
        }

        public Criteria andUserTypeGreaterThan(String value) {
            addCriterion("USER_TYPE >", value, "userType");
            return (Criteria) this;
        }

        public Criteria andUserTypeGreaterThanOrEqualTo(String value) {
            addCriterion("USER_TYPE >=", value, "userType");
            return (Criteria) this;
        }

        public Criteria andUserTypeLessThan(String value) {
            addCriterion("USER_TYPE <", value, "userType");
            return (Criteria) this;
        }

        public Criteria andUserTypeLessThanOrEqualTo(String value) {
            addCriterion("USER_TYPE <=", value, "userType");
            return (Criteria) this;
        }

        public Criteria andUserTypeLike(String value) {
            addCriterion("USER_TYPE like", value, "userType");
            return (Criteria) this;
        }

        public Criteria andUserTypeNotLike(String value) {
            addCriterion("USER_TYPE not like", value, "userType");
            return (Criteria) this;
        }

        public Criteria andUserTypeIn(List<String> values) {
            addCriterion("USER_TYPE in", values, "userType");
            return (Criteria) this;
        }

        public Criteria andUserTypeNotIn(List<String> values) {
            addCriterion("USER_TYPE not in", values, "userType");
            return (Criteria) this;
        }

        public Criteria andUserTypeBetween(String value1, String value2) {
            addCriterion("USER_TYPE between", value1, value2, "userType");
            return (Criteria) this;
        }

        public Criteria andUserTypeNotBetween(String value1, String value2) {
            addCriterion("USER_TYPE not between", value1, value2, "userType");
            return (Criteria) this;
        }

        public Criteria andDeliveryPhoneIsNull() {
            addCriterion("DELIVERY_PHONE is null");
            return (Criteria) this;
        }

        public Criteria andDeliveryPhoneIsNotNull() {
            addCriterion("DELIVERY_PHONE is not null");
            return (Criteria) this;
        }

        public Criteria andDeliveryPhoneEqualTo(String value) {
            addCriterion("DELIVERY_PHONE =", value, "deliveryPhone");
            return (Criteria) this;
        }

        public Criteria andDeliveryPhoneNotEqualTo(String value) {
            addCriterion("DELIVERY_PHONE <>", value, "deliveryPhone");
            return (Criteria) this;
        }

        public Criteria andDeliveryPhoneGreaterThan(String value) {
            addCriterion("DELIVERY_PHONE >", value, "deliveryPhone");
            return (Criteria) this;
        }

        public Criteria andDeliveryPhoneGreaterThanOrEqualTo(String value) {
            addCriterion("DELIVERY_PHONE >=", value, "deliveryPhone");
            return (Criteria) this;
        }

        public Criteria andDeliveryPhoneLessThan(String value) {
            addCriterion("DELIVERY_PHONE <", value, "deliveryPhone");
            return (Criteria) this;
        }

        public Criteria andDeliveryPhoneLessThanOrEqualTo(String value) {
            addCriterion("DELIVERY_PHONE <=", value, "deliveryPhone");
            return (Criteria) this;
        }

        public Criteria andDeliveryPhoneLike(String value) {
            addCriterion("DELIVERY_PHONE like", value, "deliveryPhone");
            return (Criteria) this;
        }

        public Criteria andDeliveryPhoneNotLike(String value) {
            addCriterion("DELIVERY_PHONE not like", value, "deliveryPhone");
            return (Criteria) this;
        }

        public Criteria andDeliveryPhoneIn(List<String> values) {
            addCriterion("DELIVERY_PHONE in", values, "deliveryPhone");
            return (Criteria) this;
        }

        public Criteria andDeliveryPhoneNotIn(List<String> values) {
            addCriterion("DELIVERY_PHONE not in", values, "deliveryPhone");
            return (Criteria) this;
        }

        public Criteria andDeliveryPhoneBetween(String value1, String value2) {
            addCriterion("DELIVERY_PHONE between", value1, value2, "deliveryPhone");
            return (Criteria) this;
        }

        public Criteria andDeliveryPhoneNotBetween(String value1, String value2) {
            addCriterion("DELIVERY_PHONE not between", value1, value2, "deliveryPhone");
            return (Criteria) this;
        }

        public Criteria andDeliveryIdCardNoIsNull() {
            addCriterion("DELIVERY_ID_CARD_NO is null");
            return (Criteria) this;
        }

        public Criteria andDeliveryIdCardNoIsNotNull() {
            addCriterion("DELIVERY_ID_CARD_NO is not null");
            return (Criteria) this;
        }

        public Criteria andDeliveryIdCardNoEqualTo(String value) {
            addCriterion("DELIVERY_ID_CARD_NO =", value, "deliveryIdCardNo");
            return (Criteria) this;
        }

        public Criteria andDeliveryIdCardNoNotEqualTo(String value) {
            addCriterion("DELIVERY_ID_CARD_NO <>", value, "deliveryIdCardNo");
            return (Criteria) this;
        }

        public Criteria andDeliveryIdCardNoGreaterThan(String value) {
            addCriterion("DELIVERY_ID_CARD_NO >", value, "deliveryIdCardNo");
            return (Criteria) this;
        }

        public Criteria andDeliveryIdCardNoGreaterThanOrEqualTo(String value) {
            addCriterion("DELIVERY_ID_CARD_NO >=", value, "deliveryIdCardNo");
            return (Criteria) this;
        }

        public Criteria andDeliveryIdCardNoLessThan(String value) {
            addCriterion("DELIVERY_ID_CARD_NO <", value, "deliveryIdCardNo");
            return (Criteria) this;
        }

        public Criteria andDeliveryIdCardNoLessThanOrEqualTo(String value) {
            addCriterion("DELIVERY_ID_CARD_NO <=", value, "deliveryIdCardNo");
            return (Criteria) this;
        }

        public Criteria andDeliveryIdCardNoLike(String value) {
            addCriterion("DELIVERY_ID_CARD_NO like", value, "deliveryIdCardNo");
            return (Criteria) this;
        }

        public Criteria andDeliveryIdCardNoNotLike(String value) {
            addCriterion("DELIVERY_ID_CARD_NO not like", value, "deliveryIdCardNo");
            return (Criteria) this;
        }

        public Criteria andDeliveryIdCardNoIn(List<String> values) {
            addCriterion("DELIVERY_ID_CARD_NO in", values, "deliveryIdCardNo");
            return (Criteria) this;
        }

        public Criteria andDeliveryIdCardNoNotIn(List<String> values) {
            addCriterion("DELIVERY_ID_CARD_NO not in", values, "deliveryIdCardNo");
            return (Criteria) this;
        }

        public Criteria andDeliveryIdCardNoBetween(String value1, String value2) {
            addCriterion("DELIVERY_ID_CARD_NO between", value1, value2, "deliveryIdCardNo");
            return (Criteria) this;
        }

        public Criteria andDeliveryIdCardNoNotBetween(String value1, String value2) {
            addCriterion("DELIVERY_ID_CARD_NO not between", value1, value2, "deliveryIdCardNo");
            return (Criteria) this;
        }

        public Criteria andDeliveryPhotoIsNull() {
            addCriterion("DELIVERY_PHOTO is null");
            return (Criteria) this;
        }

        public Criteria andDeliveryPhotoIsNotNull() {
            addCriterion("DELIVERY_PHOTO is not null");
            return (Criteria) this;
        }

        public Criteria andDeliveryPhotoEqualTo(String value) {
            addCriterion("DELIVERY_PHOTO =", value, "deliveryPhoto");
            return (Criteria) this;
        }

        public Criteria andDeliveryPhotoNotEqualTo(String value) {
            addCriterion("DELIVERY_PHOTO <>", value, "deliveryPhoto");
            return (Criteria) this;
        }

        public Criteria andDeliveryPhotoGreaterThan(String value) {
            addCriterion("DELIVERY_PHOTO >", value, "deliveryPhoto");
            return (Criteria) this;
        }

        public Criteria andDeliveryPhotoGreaterThanOrEqualTo(String value) {
            addCriterion("DELIVERY_PHOTO >=", value, "deliveryPhoto");
            return (Criteria) this;
        }

        public Criteria andDeliveryPhotoLessThan(String value) {
            addCriterion("DELIVERY_PHOTO <", value, "deliveryPhoto");
            return (Criteria) this;
        }

        public Criteria andDeliveryPhotoLessThanOrEqualTo(String value) {
            addCriterion("DELIVERY_PHOTO <=", value, "deliveryPhoto");
            return (Criteria) this;
        }

        public Criteria andDeliveryPhotoLike(String value) {
            addCriterion("DELIVERY_PHOTO like", value, "deliveryPhoto");
            return (Criteria) this;
        }

        public Criteria andDeliveryPhotoNotLike(String value) {
            addCriterion("DELIVERY_PHOTO not like", value, "deliveryPhoto");
            return (Criteria) this;
        }

        public Criteria andDeliveryPhotoIn(List<String> values) {
            addCriterion("DELIVERY_PHOTO in", values, "deliveryPhoto");
            return (Criteria) this;
        }

        public Criteria andDeliveryPhotoNotIn(List<String> values) {
            addCriterion("DELIVERY_PHOTO not in", values, "deliveryPhoto");
            return (Criteria) this;
        }

        public Criteria andDeliveryPhotoBetween(String value1, String value2) {
            addCriterion("DELIVERY_PHOTO between", value1, value2, "deliveryPhoto");
            return (Criteria) this;
        }

        public Criteria andDeliveryPhotoNotBetween(String value1, String value2) {
            addCriterion("DELIVERY_PHOTO not between", value1, value2, "deliveryPhoto");
            return (Criteria) this;
        }

        public Criteria andDeliveryEnableIsNull() {
            addCriterion("DELIVERY_ENABLE is null");
            return (Criteria) this;
        }

        public Criteria andDeliveryEnableIsNotNull() {
            addCriterion("DELIVERY_ENABLE is not null");
            return (Criteria) this;
        }

        public Criteria andDeliveryEnableEqualTo(String value) {
            addCriterion("DELIVERY_ENABLE =", value, "deliveryEnable");
            return (Criteria) this;
        }

        public Criteria andDeliveryEnableNotEqualTo(String value) {
            addCriterion("DELIVERY_ENABLE <>", value, "deliveryEnable");
            return (Criteria) this;
        }

        public Criteria andDeliveryEnableGreaterThan(String value) {
            addCriterion("DELIVERY_ENABLE >", value, "deliveryEnable");
            return (Criteria) this;
        }

        public Criteria andDeliveryEnableGreaterThanOrEqualTo(String value) {
            addCriterion("DELIVERY_ENABLE >=", value, "deliveryEnable");
            return (Criteria) this;
        }

        public Criteria andDeliveryEnableLessThan(String value) {
            addCriterion("DELIVERY_ENABLE <", value, "deliveryEnable");
            return (Criteria) this;
        }

        public Criteria andDeliveryEnableLessThanOrEqualTo(String value) {
            addCriterion("DELIVERY_ENABLE <=", value, "deliveryEnable");
            return (Criteria) this;
        }

        public Criteria andDeliveryEnableLike(String value) {
            addCriterion("DELIVERY_ENABLE like", value, "deliveryEnable");
            return (Criteria) this;
        }

        public Criteria andDeliveryEnableNotLike(String value) {
            addCriterion("DELIVERY_ENABLE not like", value, "deliveryEnable");
            return (Criteria) this;
        }

        public Criteria andDeliveryEnableIn(List<String> values) {
            addCriterion("DELIVERY_ENABLE in", values, "deliveryEnable");
            return (Criteria) this;
        }

        public Criteria andDeliveryEnableNotIn(List<String> values) {
            addCriterion("DELIVERY_ENABLE not in", values, "deliveryEnable");
            return (Criteria) this;
        }

        public Criteria andDeliveryEnableBetween(String value1, String value2) {
            addCriterion("DELIVERY_ENABLE between", value1, value2, "deliveryEnable");
            return (Criteria) this;
        }

        public Criteria andDeliveryEnableNotBetween(String value1, String value2) {
            addCriterion("DELIVERY_ENABLE not between", value1, value2, "deliveryEnable");
            return (Criteria) this;
        }

        public Criteria andCreatedTimeIsNull() {
            addCriterion("CREATED_TIME is null");
            return (Criteria) this;
        }

        public Criteria andCreatedTimeIsNotNull() {
            addCriterion("CREATED_TIME is not null");
            return (Criteria) this;
        }

        public Criteria andCreatedTimeEqualTo(Date value) {
            addCriterion("CREATED_TIME =", value, "createdTime");
            return (Criteria) this;
        }

        public Criteria andCreatedTimeNotEqualTo(Date value) {
            addCriterion("CREATED_TIME <>", value, "createdTime");
            return (Criteria) this;
        }

        public Criteria andCreatedTimeGreaterThan(Date value) {
            addCriterion("CREATED_TIME >", value, "createdTime");
            return (Criteria) this;
        }

        public Criteria andCreatedTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("CREATED_TIME >=", value, "createdTime");
            return (Criteria) this;
        }

        public Criteria andCreatedTimeLessThan(Date value) {
            addCriterion("CREATED_TIME <", value, "createdTime");
            return (Criteria) this;
        }

        public Criteria andCreatedTimeLessThanOrEqualTo(Date value) {
            addCriterion("CREATED_TIME <=", value, "createdTime");
            return (Criteria) this;
        }

        public Criteria andCreatedTimeIn(List<Date> values) {
            addCriterion("CREATED_TIME in", values, "createdTime");
            return (Criteria) this;
        }

        public Criteria andCreatedTimeNotIn(List<Date> values) {
            addCriterion("CREATED_TIME not in", values, "createdTime");
            return (Criteria) this;
        }

        public Criteria andCreatedTimeBetween(Date value1, Date value2) {
            addCriterion("CREATED_TIME between", value1, value2, "createdTime");
            return (Criteria) this;
        }

        public Criteria andCreatedTimeNotBetween(Date value1, Date value2) {
            addCriterion("CREATED_TIME not between", value1, value2, "createdTime");
            return (Criteria) this;
        }

        public Criteria andLastUpdateTimeIsNull() {
            addCriterion("LAST_UPDATE_TIME is null");
            return (Criteria) this;
        }

        public Criteria andLastUpdateTimeIsNotNull() {
            addCriterion("LAST_UPDATE_TIME is not null");
            return (Criteria) this;
        }

        public Criteria andLastUpdateTimeEqualTo(Date value) {
            addCriterion("LAST_UPDATE_TIME =", value, "lastUpdateTime");
            return (Criteria) this;
        }

        public Criteria andLastUpdateTimeNotEqualTo(Date value) {
            addCriterion("LAST_UPDATE_TIME <>", value, "lastUpdateTime");
            return (Criteria) this;
        }

        public Criteria andLastUpdateTimeGreaterThan(Date value) {
            addCriterion("LAST_UPDATE_TIME >", value, "lastUpdateTime");
            return (Criteria) this;
        }

        public Criteria andLastUpdateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("LAST_UPDATE_TIME >=", value, "lastUpdateTime");
            return (Criteria) this;
        }

        public Criteria andLastUpdateTimeLessThan(Date value) {
            addCriterion("LAST_UPDATE_TIME <", value, "lastUpdateTime");
            return (Criteria) this;
        }

        public Criteria andLastUpdateTimeLessThanOrEqualTo(Date value) {
            addCriterion("LAST_UPDATE_TIME <=", value, "lastUpdateTime");
            return (Criteria) this;
        }

        public Criteria andLastUpdateTimeIn(List<Date> values) {
            addCriterion("LAST_UPDATE_TIME in", values, "lastUpdateTime");
            return (Criteria) this;
        }

        public Criteria andLastUpdateTimeNotIn(List<Date> values) {
            addCriterion("LAST_UPDATE_TIME not in", values, "lastUpdateTime");
            return (Criteria) this;
        }

        public Criteria andLastUpdateTimeBetween(Date value1, Date value2) {
            addCriterion("LAST_UPDATE_TIME between", value1, value2, "lastUpdateTime");
            return (Criteria) this;
        }

        public Criteria andLastUpdateTimeNotBetween(Date value1, Date value2) {
            addCriterion("LAST_UPDATE_TIME not between", value1, value2, "lastUpdateTime");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table delivery
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table delivery
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}