package com.yaya.orderSystem.delivery.model;

import java.io.Serializable;
import java.util.Date;

public class Delivery implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column delivery.DELIVERY_ID
     *
     * @mbg.generated
     */
    private String deliveryId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column delivery.DELIVERY_LOGIN_NAME
     *
     * @mbg.generated
     */
    private String deliveryLoginName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column delivery.DELIVERY_NAME
     *
     * @mbg.generated
     */
    private String deliveryName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column delivery.DELIVERY_PASSWORD
     *
     * @mbg.generated
     */
    private String deliveryPassword;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column delivery.SALT
     *
     * @mbg.generated
     */
    private String salt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column delivery.USER_TYPE
     *
     * @mbg.generated
     */
    private String userType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column delivery.DELIVERY_PHONE
     *
     * @mbg.generated
     */
    private String deliveryPhone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column delivery.DELIVERY_ID_CARD_NO
     *
     * @mbg.generated
     */
    private String deliveryIdCardNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column delivery.DELIVERY_PHOTO
     *
     * @mbg.generated
     */
    private String deliveryPhoto;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column delivery.DELIVERY_ENABLE
     *
     * @mbg.generated
     */
    private String deliveryEnable;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column delivery.CREATED_TIME
     *
     * @mbg.generated
     */
    private Date createdTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column delivery.LAST_UPDATE_TIME
     *
     * @mbg.generated
     */
    private Date lastUpdateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table delivery
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column delivery.DELIVERY_ID
     *
     * @return the value of delivery.DELIVERY_ID
     *
     * @mbg.generated
     */
    public String getDeliveryId() {
        return deliveryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column delivery.DELIVERY_ID
     *
     * @param deliveryId the value for delivery.DELIVERY_ID
     *
     * @mbg.generated
     */
    public void setDeliveryId(String deliveryId) {
        this.deliveryId = deliveryId == null ? null : deliveryId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column delivery.DELIVERY_LOGIN_NAME
     *
     * @return the value of delivery.DELIVERY_LOGIN_NAME
     *
     * @mbg.generated
     */
    public String getDeliveryLoginName() {
        return deliveryLoginName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column delivery.DELIVERY_LOGIN_NAME
     *
     * @param deliveryLoginName the value for delivery.DELIVERY_LOGIN_NAME
     *
     * @mbg.generated
     */
    public void setDeliveryLoginName(String deliveryLoginName) {
        this.deliveryLoginName = deliveryLoginName == null ? null : deliveryLoginName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column delivery.DELIVERY_NAME
     *
     * @return the value of delivery.DELIVERY_NAME
     *
     * @mbg.generated
     */
    public String getDeliveryName() {
        return deliveryName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column delivery.DELIVERY_NAME
     *
     * @param deliveryName the value for delivery.DELIVERY_NAME
     *
     * @mbg.generated
     */
    public void setDeliveryName(String deliveryName) {
        this.deliveryName = deliveryName == null ? null : deliveryName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column delivery.DELIVERY_PASSWORD
     *
     * @return the value of delivery.DELIVERY_PASSWORD
     *
     * @mbg.generated
     */
    public String getDeliveryPassword() {
        return deliveryPassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column delivery.DELIVERY_PASSWORD
     *
     * @param deliveryPassword the value for delivery.DELIVERY_PASSWORD
     *
     * @mbg.generated
     */
    public void setDeliveryPassword(String deliveryPassword) {
        this.deliveryPassword = deliveryPassword == null ? null : deliveryPassword.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column delivery.SALT
     *
     * @return the value of delivery.SALT
     *
     * @mbg.generated
     */
    public String getSalt() {
        return salt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column delivery.SALT
     *
     * @param salt the value for delivery.SALT
     *
     * @mbg.generated
     */
    public void setSalt(String salt) {
        this.salt = salt == null ? null : salt.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column delivery.USER_TYPE
     *
     * @return the value of delivery.USER_TYPE
     *
     * @mbg.generated
     */
    public String getUserType() {
        return userType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column delivery.USER_TYPE
     *
     * @param userType the value for delivery.USER_TYPE
     *
     * @mbg.generated
     */
    public void setUserType(String userType) {
        this.userType = userType == null ? null : userType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column delivery.DELIVERY_PHONE
     *
     * @return the value of delivery.DELIVERY_PHONE
     *
     * @mbg.generated
     */
    public String getDeliveryPhone() {
        return deliveryPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column delivery.DELIVERY_PHONE
     *
     * @param deliveryPhone the value for delivery.DELIVERY_PHONE
     *
     * @mbg.generated
     */
    public void setDeliveryPhone(String deliveryPhone) {
        this.deliveryPhone = deliveryPhone == null ? null : deliveryPhone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column delivery.DELIVERY_ID_CARD_NO
     *
     * @return the value of delivery.DELIVERY_ID_CARD_NO
     *
     * @mbg.generated
     */
    public String getDeliveryIdCardNo() {
        return deliveryIdCardNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column delivery.DELIVERY_ID_CARD_NO
     *
     * @param deliveryIdCardNo the value for delivery.DELIVERY_ID_CARD_NO
     *
     * @mbg.generated
     */
    public void setDeliveryIdCardNo(String deliveryIdCardNo) {
        this.deliveryIdCardNo = deliveryIdCardNo == null ? null : deliveryIdCardNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column delivery.DELIVERY_PHOTO
     *
     * @return the value of delivery.DELIVERY_PHOTO
     *
     * @mbg.generated
     */
    public String getDeliveryPhoto() {
        return deliveryPhoto;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column delivery.DELIVERY_PHOTO
     *
     * @param deliveryPhoto the value for delivery.DELIVERY_PHOTO
     *
     * @mbg.generated
     */
    public void setDeliveryPhoto(String deliveryPhoto) {
        this.deliveryPhoto = deliveryPhoto == null ? null : deliveryPhoto.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column delivery.DELIVERY_ENABLE
     *
     * @return the value of delivery.DELIVERY_ENABLE
     *
     * @mbg.generated
     */
    public String getDeliveryEnable() {
        return deliveryEnable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column delivery.DELIVERY_ENABLE
     *
     * @param deliveryEnable the value for delivery.DELIVERY_ENABLE
     *
     * @mbg.generated
     */
    public void setDeliveryEnable(String deliveryEnable) {
        this.deliveryEnable = deliveryEnable == null ? null : deliveryEnable.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column delivery.CREATED_TIME
     *
     * @return the value of delivery.CREATED_TIME
     *
     * @mbg.generated
     */
    public Date getCreatedTime() {
        return createdTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column delivery.CREATED_TIME
     *
     * @param createdTime the value for delivery.CREATED_TIME
     *
     * @mbg.generated
     */
    public void setCreatedTime(Date createdTime) {
        this.createdTime = createdTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column delivery.LAST_UPDATE_TIME
     *
     * @return the value of delivery.LAST_UPDATE_TIME
     *
     * @mbg.generated
     */
    public Date getLastUpdateTime() {
        return lastUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column delivery.LAST_UPDATE_TIME
     *
     * @param lastUpdateTime the value for delivery.LAST_UPDATE_TIME
     *
     * @mbg.generated
     */
    public void setLastUpdateTime(Date lastUpdateTime) {
        this.lastUpdateTime = lastUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table delivery
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", deliveryId=").append(deliveryId);
        sb.append(", deliveryLoginName=").append(deliveryLoginName);
        sb.append(", deliveryName=").append(deliveryName);
        sb.append(", deliveryPassword=").append(deliveryPassword);
        sb.append(", salt=").append(salt);
        sb.append(", userType=").append(userType);
        sb.append(", deliveryPhone=").append(deliveryPhone);
        sb.append(", deliveryIdCardNo=").append(deliveryIdCardNo);
        sb.append(", deliveryPhoto=").append(deliveryPhoto);
        sb.append(", deliveryEnable=").append(deliveryEnable);
        sb.append(", createdTime=").append(createdTime);
        sb.append(", lastUpdateTime=").append(lastUpdateTime);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}