package com.yaya.orderSystem.delivery.dao;

import com.yaya.orderSystem.delivery.model.Delivery;
import com.yaya.orderSystem.delivery.model.DeliveryExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface DeliveryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table delivery
     *
     * @mbg.generated
     */
    long countByExample(DeliveryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table delivery
     *
     * @mbg.generated
     */
    int deleteByExample(DeliveryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table delivery
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String deliveryId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table delivery
     *
     * @mbg.generated
     */
    int insert(Delivery record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table delivery
     *
     * @mbg.generated
     */
    int insertSelective(Delivery record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table delivery
     *
     * @mbg.generated
     */
    List<Delivery> selectByExample(DeliveryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table delivery
     *
     * @mbg.generated
     */
    Delivery selectByPrimaryKey(String deliveryId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table delivery
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") Delivery record, @Param("example") DeliveryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table delivery
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") Delivery record, @Param("example") DeliveryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table delivery
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Delivery record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table delivery
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Delivery record);
}