package com.yaya.orderSystem.delivery.dao;

import com.yaya.orderSystem.delivery.model.DeliveryOrder;
import com.yaya.orderSystem.delivery.model.DeliveryOrderExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface DeliveryOrderMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table delivery_order
     *
     * @mbg.generated
     */
    long countByExample(DeliveryOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table delivery_order
     *
     * @mbg.generated
     */
    int deleteByExample(DeliveryOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table delivery_order
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String deliveryOrderId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table delivery_order
     *
     * @mbg.generated
     */
    int insert(DeliveryOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table delivery_order
     *
     * @mbg.generated
     */
    int insertSelective(DeliveryOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table delivery_order
     *
     * @mbg.generated
     */
    List<DeliveryOrder> selectByExample(DeliveryOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table delivery_order
     *
     * @mbg.generated
     */
    DeliveryOrder selectByPrimaryKey(String deliveryOrderId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table delivery_order
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") DeliveryOrder record, @Param("example") DeliveryOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table delivery_order
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") DeliveryOrder record, @Param("example") DeliveryOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table delivery_order
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(DeliveryOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table delivery_order
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(DeliveryOrder record);
}