package com.yaya.order.dao;

import com.yaya.order.model.DeliveryOrder;
import com.yaya.order.model.DeliveryOrderExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface DeliveryOrderMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table delivery_order
     *
     * @mbg.generated
     */
    long countByExample(DeliveryOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table delivery_order
     *
     * @mbg.generated
     */
    int deleteByExample(DeliveryOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table delivery_order
     *
     * @mbg.generated
     */
    int insert(DeliveryOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table delivery_order
     *
     * @mbg.generated
     */
    int insertSelective(DeliveryOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table delivery_order
     *
     * @mbg.generated
     */
    List<DeliveryOrder> selectByExample(DeliveryOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table delivery_order
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") DeliveryOrder record, @Param("example") DeliveryOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table delivery_order
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") DeliveryOrder record, @Param("example") DeliveryOrderExample example);
}