package com.yaya.order.dao;

import com.yaya.order.model.MerchantOrder;
import com.yaya.order.model.MerchantOrderExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface MerchantOrderMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table merchant_order
     *
     * @mbg.generated
     */
    long countByExample(MerchantOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table merchant_order
     *
     * @mbg.generated
     */
    int deleteByExample(MerchantOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table merchant_order
     *
     * @mbg.generated
     */
    int insert(MerchantOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table merchant_order
     *
     * @mbg.generated
     */
    int insertSelective(MerchantOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table merchant_order
     *
     * @mbg.generated
     */
    List<MerchantOrder> selectByExample(MerchantOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table merchant_order
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") MerchantOrder record, @Param("example") MerchantOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table merchant_order
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") MerchantOrder record, @Param("example") MerchantOrderExample example);
}