-- MySQL Script generated by MySQL Workbench
-- Wed Oct 24 17:30:57 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema orderSystem
-- -----------------------------------------------------
-- 订餐系统

-- -----------------------------------------------------
-- Schema orderSystem
--
-- 订餐系统
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `orderSystem` DEFAULT CHARACTER SET utf8 ;
USE `orderSystem` ;

-- -----------------------------------------------------
-- Table `orderSystem`.`merchant`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `orderSystem`.`merchant` (
  `MERCHANT_ID` VARCHAR(40) NOT NULL COMMENT '商家ID',
  `MERCHANT_LOGIN_NAME` VARCHAR(200) NOT NULL COMMENT '商家登陆的用户名',
  `MERCHANT_NAME` VARCHAR(200) NOT NULL COMMENT '商家名称',
  `MERCHANT_PASSWORD` VARCHAR(150) NOT NULL COMMENT '商家登陆密码',
  `SALT` VARCHAR(10) NOT NULL COMMENT '密码盐值',
  `USER_TYPE` VARCHAR(2) NOT NULL DEFAULT '01' COMMENT '用户类型01---商家',
  `MERCHANT_TEL_PHONE` VARCHAR(20) NULL COMMENT '商家座机号码',
  `MERCHANT_MOBILEPHONE` VARCHAR(20) NULL COMMENT '商家的手机号码',
  `MERCHANT_BUSINESS_LICENSE` VARCHAR(25) NOT NULL COMMENT '营业执照编号',
  `MERCHANT_PHOTO` VARCHAR(45) NULL COMMENT '商家照片',
  `MERCHANT_ADDRESS` VARCHAR(300) NOT NULL COMMENT '商家地址',
  `MERCHANT_LONGITUDE` DECIMAL(20,15) NOT NULL COMMENT '商家的位置经度',
  `MERCHANT_LATITUDE` DECIMAL(20,15) NOT NULL COMMENT '商家位置的纬度',
  `MERCHANT_ENABLE` VARCHAR(2) NOT NULL DEFAULT '01' COMMENT '商家是否可用00---不可用01---可用',
  `CREATE_TIME` DATETIME NOT NULL COMMENT '创建时间',
  `LAST_UPDATE_TIME` DATETIME NOT NULL COMMENT '最后更新时间',
  PRIMARY KEY (`MERCHANT_ID`),
  UNIQUE INDEX `LOGIN_NAME_UNIQUE` (`MERCHANT_LOGIN_NAME` ASC))
ENGINE = InnoDB
COMMENT = '商家表';


-- -----------------------------------------------------
-- Table `orderSystem`.`delivery`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `orderSystem`.`delivery` (
  `DELIVERY_ID` VARCHAR(40) NOT NULL COMMENT '送餐员ID',
  `DELIVERY_LOGIN_NAME` VARCHAR(200) NOT NULL COMMENT '送餐员登陆名',
  `DELIVERY_NAME` VARCHAR(200) NOT NULL COMMENT '送餐员姓名',
  `DELIVERY_PASSWORD` VARCHAR(150) NOT NULL COMMENT '送餐员登陆密码',
  `SALT` VARCHAR(10) NOT NULL COMMENT '密码盐值',
  `USER_TYPE` VARCHAR(2) NOT NULL DEFAULT '02' COMMENT '用户类型02----送餐员',
  `DELIVERY_PHONE` VARCHAR(20) NOT NULL COMMENT '送餐员电话',
  `DELIVERY_ID_CARD_NO` VARCHAR(20) NOT NULL COMMENT '送餐员身份证号码',
  `DELIVERY_PHOTO` VARCHAR(45) NULL COMMENT '送餐员照片',
  `DELIVERY_ENABLE` VARCHAR(2) NOT NULL DEFAULT '01' COMMENT '送餐员是否可用00---不可用01---可用',
  `CREATED_TIME` DATETIME NOT NULL COMMENT '创建时间',
  `LAST_UPDATE_TIME` DATETIME NOT NULL COMMENT '最后修改时间',
  PRIMARY KEY (`DELIVERY_ID`))
ENGINE = InnoDB
COMMENT = '送餐员表';


-- -----------------------------------------------------
-- Table `orderSystem`.`client`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `orderSystem`.`client` (
  `CLIENT_ID` VARCHAR(40) NOT NULL COMMENT '客户ID',
  `CLIENT_LOGIN_NAME` VARCHAR(200) NOT NULL COMMENT '客户登陆名',
  `CLIENT_NAME` VARCHAR(200) NOT NULL COMMENT '客户姓名',
  `CLIENT_PASSWORD` VARCHAR(150) NOT NULL COMMENT '客户登陆密码',
  `SALT` VARCHAR(10) NOT NULL COMMENT '密码盐值',
  `USER_TYPE` VARCHAR(2) NOT NULL DEFAULT '03' COMMENT '用户类型03---点餐客户',
  `CLIENT_PHONE` VARCHAR(20) NOT NULL COMMENT '客户联系电话',
  `CREATE_TIME` DATETIME NOT NULL COMMENT '创建时间',
  `LAST_UPDATE_TIME` DATETIME NOT NULL COMMENT '最后更新时间',
  PRIMARY KEY (`CLIENT_ID`))
ENGINE = InnoDB
COMMENT = '点餐的普通用户表';


-- -----------------------------------------------------
-- Table `orderSystem`.`client_address`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `orderSystem`.`client_address` (
  `CLIENT_ADDRESS_ID` VARCHAR(40) NOT NULL COMMENT '点餐客户地址ID',
  `CLIENT_ID` VARCHAR(40) NOT NULL COMMENT '点餐客户ID',
  `CLIENT_ADDRESS` VARCHAR(300) NOT NULL COMMENT '客户地址',
  `CREATE_DATE` DATE NOT NULL COMMENT '创建日期',
  `LAST_UPDATE_DATE` DATE NOT NULL COMMENT '最后更新日期',
  PRIMARY KEY (`CLIENT_ADDRESS_ID`))
ENGINE = InnoDB
COMMENT = '点餐客户地址表';


-- -----------------------------------------------------
-- Table `orderSystem`.`product`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `orderSystem`.`product` (
  `PRODUCT_ID` VARCHAR(40) NOT NULL COMMENT '产品ID',
  `MERCHANT_ID` VARCHAR(40) NOT NULL COMMENT '商家ID',
  `PRODUCT_NAME` VARCHAR(50) NOT NULL COMMENT '产品名称',
  `PRODUCT_DESCRIPTION` VARCHAR(200) NULL COMMENT '产品描述',
  `PRODUCT_PRICE` DECIMAL(10,4) NULL DEFAULT 0 COMMENT '产品价格',
  `PRODUCT_PICTURE` VARCHAR(45) NOT NULL COMMENT '产品图片',
  `PRODUCT_ORDER_COUNT` INT NOT NULL DEFAULT 0 COMMENT '产品订取次数',
  `PRODUCT_ENABLE` VARCHAR(2) NOT NULL DEFAULT '01' COMMENT '产品是否可用00--不可用01---可用',
  `CREATE_TIME` DATETIME NOT NULL COMMENT '产品创建时间',
  `LAST_UPDATE_TIME` DATETIME NOT NULL COMMENT '最后更新时间',
  PRIMARY KEY (`PRODUCT_ID`))
ENGINE = InnoDB
COMMENT = '商家的产品表';


-- -----------------------------------------------------
-- Table `orderSystem`.`evaluate`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `orderSystem`.`evaluate` (
  `EVALUATE_ID` VARCHAR(40) NOT NULL COMMENT '评价ID',
  `EVALUATE_DESCRIPTION` VARCHAR(200) NOT NULL COMMENT '评论描述',
  `EVALUATE_PARENT_ID` VARCHAR(40) NULL COMMENT '用于确定回复评论的来源评论ID',
  `EVALUATE_PICTURE` VARCHAR(45) NULL COMMENT '评论中上传的图片',
  `CREATE_TIME` DATETIME NOT NULL COMMENT '创建时间',
  PRIMARY KEY (`EVALUATE_ID`))
ENGINE = InnoDB
COMMENT = '商家评价表';


-- -----------------------------------------------------
-- Table `orderSystem`.`merchant_evaluate`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `orderSystem`.`merchant_evaluate` (
  `MERCHANT_EVALUATE_ID` VARCHAR(40) NOT NULL COMMENT '商家评论中间表ID',
  `EVALUATE_ID` VARCHAR(40) NOT NULL COMMENT '评论ID',
  `ORDER_ID` VARCHAR(40) NOT NULL COMMENT '订单ID',
  `USER_ID` VARCHAR(40) NOT NULL COMMENT '用户ID',
  `USER_TYPE` VARCHAR(2) NOT NULL COMMENT '用户类型01---点餐客户02---商家用户',
  PRIMARY KEY (`MERCHANT_EVALUATE_ID`))
ENGINE = InnoDB
COMMENT = '商家评论中间表';


-- -----------------------------------------------------
-- Table `orderSystem`.`merchant_evaluate_rate`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `orderSystem`.`merchant_evaluate_rate` (
  `EVALUATE_RATE_ID` VARCHAR(40) NOT NULL COMMENT '商家评价率ID',
  `MERCHANT_ID` VARCHAR(40) NOT NULL COMMENT '商家ID',
  `GOOD_EVALUATE_COUNT` INT NOT NULL DEFAULT 0 COMMENT '好评次数',
  `ORDINARY_EVALUATE_COUNT` INT NOT NULL DEFAULT 0 COMMENT '中评次数',
  `BAD_EVALUATE_COUNT` INT NOT NULL DEFAULT 0 COMMENT '差评次数',
  `MERCHANT_EVALUATE_SCORE` DECIMAL(5,2) NOT NULL DEFAULT 0 COMMENT '商家评价得分,好评得1分，中评得0.5分，差评扣1分',
  PRIMARY KEY (`EVALUATE_RATE_ID`))
ENGINE = InnoDB
COMMENT = '商家存储好评、中评、差评次数表';


-- -----------------------------------------------------
-- Table `orderSystem`.`client_evaluate`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `orderSystem`.`client_evaluate` (
  `CLIENT_EVALUATE_ID` VARCHAR(40) NOT NULL COMMENT '用户评分ID',
  `ORDER_ID` VARCHAR(40) NOT NULL COMMENT '订单ID',
  `CLIENT_ID` VARCHAR(40) NOT NULL COMMENT '客户ID',
  `EVALUATE_ID` VARCHAR(40) NOT NULL COMMENT '评论ID',
  PRIMARY KEY (`CLIENT_EVALUATE_ID`))
ENGINE = InnoDB
COMMENT = '用户评分表';


-- -----------------------------------------------------
-- Table `orderSystem`.`product_evaluate`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `orderSystem`.`product_evaluate` (
  `PRODUCT_EVALUATE_ID` VARCHAR(40) NOT NULL COMMENT '产品评价ID',
  `PRODUCT_ID` VARCHAR(40) NOT NULL COMMENT '产品ID',
  `EVALUATE_ID` VARCHAR(40) NOT NULL COMMENT '评价ID',
  PRIMARY KEY (`PRODUCT_EVALUATE_ID`))
ENGINE = InnoDB
COMMENT = '产品评价表';


-- -----------------------------------------------------
-- Table `orderSystem`.`orders`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `orderSystem`.`orders` (
  `ORDER_ID` VARCHAR(40) NOT NULL COMMENT '订单ID',
  `CLIENT_ID` VARCHAR(40) NOT NULL COMMENT '客户ID',
  `MERCHANT_ID` VARCHAR(40) NOT NULL COMMENT '商家ID',
  `ORDER_STATUS` VARCHAR(2) NOT NULL DEFAULT '01' COMMENT '订单状态00---客户取消订单01---客户生成订单02---商家接受订单03---商家拒绝订单04----商家完成订单05----送餐员接收订单06----送餐员配送订单07----送餐员送达订单08----客户收到订单',
  `ORDER_TOTAL_AMOUNT` DECIMAL(15,4) NOT NULL DEFAULT 0 COMMENT '订单金额',
  `ORDER_DESC` VARCHAR(200) NULL COMMENT '订单描述',
  `CREATE_TIME` DATETIME NOT NULL COMMENT '创建时间',
  PRIMARY KEY (`ORDER_ID`))
ENGINE = InnoDB
COMMENT = '订单表';


-- -----------------------------------------------------
-- Table `orderSystem`.`merchant_order`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `orderSystem`.`merchant_order` (
  `MERCHANT_ORDER_ID` VARCHAR(40) NOT NULL COMMENT '商家订单ID',
  `MERCHANT_ID` VARCHAR(40) NOT NULL COMMENT '商家ID',
  `ORDER_ID` VARCHAR(40) NOT NULL COMMENT '订单ID',
  `MERCHANT_ORDER_DESC` VARCHAR(200) NULL COMMENT '商家订单处理描述',
  `CREATE_TIME` DATETIME NOT NULL COMMENT '创建时间',
  `LAST_UPDATE_TIME` DATETIME NOT NULL COMMENT '最后更新时间',
  PRIMARY KEY (`MERCHANT_ORDER_ID`))
ENGINE = InnoDB
COMMENT = '商家订单关系表';


-- -----------------------------------------------------
-- Table `orderSystem`.`order_product`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `orderSystem`.`order_product` (
  `ORDER_PRODUCT_ID` VARCHAR(40) NOT NULL COMMENT '订单产品ID',
  `ORDER_ID` VARCHAR(40) NOT NULL COMMENT '订单ID',
  `PRODUCT_ID` VARCHAR(40) NOT NULL COMMENT '产品ID',
  `PRODUCT_COUNT` INT NOT NULL COMMENT '产品的数量',
  PRIMARY KEY (`ORDER_PRODUCT_ID`))
ENGINE = InnoDB
COMMENT = '订单产品信息表';


-- -----------------------------------------------------
-- Table `orderSystem`.`delivery_order`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `orderSystem`.`delivery_order` (
  `DELIVERY_ORDER_ID` VARCHAR(40) NOT NULL COMMENT '送餐员订单ID',
  `DELIVERY_ID` VARCHAR(40) NOT NULL COMMENT '送餐员ID',
  `ORDER_ID` VARCHAR(40) NOT NULL COMMENT '订单ID',
  `CREATE_TIME` DATETIME NOT NULL COMMENT '创建时间',
  PRIMARY KEY (`DELIVERY_ORDER_ID`))
ENGINE = InnoDB
COMMENT = '送餐员订单表';


-- -----------------------------------------------------
-- Table `orderSystem`.`merchant_all_product_discount_rate`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `orderSystem`.`merchant_all_product_discount_rate` (
  `ALL_PRODUCT_DISCOUNT_RATE_ID` VARCHAR(40) NOT NULL COMMENT '折扣率ID',
  `MERCHANT_ID` VARCHAR(40) NOT NULL COMMENT '商家ID',
  `ALL_PRODUCT_DISCOUNT_RATE` DECIMAL(2,2) NOT NULL COMMENT '折扣率',
  `DISCOUNT_DESC` VARCHAR(200) NOT NULL COMMENT '折扣描述',
  `LAST_UPDATE_TIME` DATETIME NOT NULL COMMENT '最后更新时间',
  PRIMARY KEY (`ALL_PRODUCT_DISCOUNT_RATE_ID`))
ENGINE = InnoDB
COMMENT = '商家自定义所有产品的统一折扣率表';


-- -----------------------------------------------------
-- Table `orderSystem`.`merchant_all_product_discount_rate_history`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `orderSystem`.`merchant_all_product_discount_rate_history` (
  `ALL_PRODUCT_DISCOUNT_RATE_ID` VARCHAR(40) NOT NULL COMMENT '折扣率ID',
  `MERCHANT_ID` VARCHAR(40) NOT NULL COMMENT '商家ID',
  `ALL_PRODUCT_DISCOUNT_RATE` DECIMAL(2,2) NOT NULL COMMENT '折扣率',
  `DISCOUNT_DESC` VARCHAR(200) NOT NULL COMMENT '折扣描述',
  `CREATE_DATE` DATETIME NOT NULL COMMENT '创建时间',
  PRIMARY KEY (`ALL_PRODUCT_DISCOUNT_RATE_ID`))
ENGINE = InnoDB
COMMENT = '商家自定义所有产品的统一折扣率表历史表';


-- -----------------------------------------------------
-- Table `orderSystem`.`merchant_signal_product_discount_price`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `orderSystem`.`merchant_signal_product_discount_price` (
  `PRODUCT_DISCOUNT_PRICE_ID` VARCHAR(40) NOT NULL COMMENT '商家单个产品价格ID',
  `MERCHANT_ID` VARCHAR(40) NOT NULL COMMENT '商家ID',
  `PRODUCT_ID` VARCHAR(40) NOT NULL COMMENT '产品ID',
  `DISCOUNT_PRICE` DECIMAL(10,4) NOT NULL COMMENT '折扣价格',
  `DISCOUNT_DESC` VARCHAR(200) NOT NULL COMMENT '折扣描述',
  `LAST_UPDATE_TIME` DATETIME NOT NULL COMMENT '最后更新时间',
  PRIMARY KEY (`PRODUCT_DISCOUNT_PRICE_ID`))
ENGINE = InnoDB
COMMENT = '商家单个产品折扣价格表';


-- -----------------------------------------------------
-- Table `orderSystem`.`merchant_signal_product_discount_price_history`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `orderSystem`.`merchant_signal_product_discount_price_history` (
  `PRODUCT_DISCOUNT_PRICE_ID` VARCHAR(40) NOT NULL COMMENT '商家单个产品价格ID',
  `MERCHANT_ID` VARCHAR(40) NOT NULL COMMENT '商家ID',
  `PRODUCT_ID` VARCHAR(40) NOT NULL COMMENT '产品ID',
  `DISCOUNT_PRICE` DECIMAL(10,4) NOT NULL COMMENT '折扣价格',
  `CREATE_TIME` DATETIME NOT NULL COMMENT '创建时间',
  PRIMARY KEY (`PRODUCT_DISCOUNT_PRICE_ID`))
ENGINE = InnoDB
COMMENT = '商家单个产品折扣价格历史表';


-- -----------------------------------------------------
-- Table `orderSystem`.`other_public_discount`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `orderSystem`.`other_public_discount` (
  `PUBLIC_DISCOUNT_ID` VARCHAR(40) NOT NULL COMMENT '公共折扣ID',
  `DISCOUNT_AMOUNT` DECIMAL(10,4) NOT NULL COMMENT '折扣金额',
  `DISCOUNT_DESC` VARCHAR(100) NOT NULL COMMENT '折扣描述',
  `DISCOUNT_BEGIN_DATE` DATE NOT NULL COMMENT '折扣开始日期',
  `DISCOUNT_END_DATE` DATE NOT NULL COMMENT '折扣结束日期',
  `DISCOUNT_STATUS` VARCHAR(2) NOT NULL COMMENT '折扣状态00---无效01---有效',
  `LAST_UPDATE_TIME` DATETIME NOT NULL COMMENT '最后更新时间',
  PRIMARY KEY (`PUBLIC_DISCOUNT_ID`))
ENGINE = InnoDB
COMMENT = '其他公共优惠活动表';


-- -----------------------------------------------------
-- Table `orderSystem`.`merchant_product_order_bill`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `orderSystem`.`merchant_product_order_bill` (
  `PRODUCT_ORDER_BILL_ID` VARCHAR(40) NOT NULL COMMENT '产品订单的支付ID',
  `MERCHANT_ID` VARCHAR(40) NOT NULL COMMENT '商家ID',
  `PRODUCT_ID` VARCHAR(40) NOT NULL COMMENT '产品ID',
  `ORDER_ID` VARCHAR(40) NOT NULL COMMENT '订单ID',
  `PAY_AMOUNT` DECIMAL(10,4) NOT NULL COMMENT '支付金额',
  `OVER_STATUS` VARCHAR(2) NOT NULL COMMENT '订单收取完成状态00--客户未收取01---客户已收取',
  `CREATE_TIME` DATETIME NOT NULL COMMENT '创建时间',
  PRIMARY KEY (`PRODUCT_ORDER_BILL_ID`))
ENGINE = InnoDB
COMMENT = '商家的产品订单的收取金额表';


-- -----------------------------------------------------
-- Table `orderSystem`.`merchant_order_sum_bill`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `orderSystem`.`merchant_order_sum_bill` (
  `ORDER_SUM_BILL_ID` VARCHAR(40) NOT NULL COMMENT '商家订单总共金额ID',
  `MERCHANT_ID` VARCHAR(40) NOT NULL COMMENT '商家ID',
  `ORDER_ID` VARCHAR(40) NOT NULL COMMENT '订单ID',
  `PAY_SUM_AMOUNT` DECIMAL(10,4) NOT NULL COMMENT '订单总共金额',
  `CREATE_TIME` DATETIME NOT NULL COMMENT '创建时间',
  PRIMARY KEY (`ORDER_SUM_BILL_ID`))
ENGINE = InnoDB
COMMENT = '商家订单总共金额表';


-- -----------------------------------------------------
-- Table `orderSystem`.`merchant_delivery_order_bill`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `orderSystem`.`merchant_delivery_order_bill` (
  `DELIVERY_ORDER_BILL_ID` VARCHAR(40) NOT NULL COMMENT '商家送餐员订单支付ID',
  `MERCHANT_ID` VARCHAR(40) NOT NULL COMMENT '商家ID',
  `DELIVERY_ID` VARCHAR(40) NOT NULL COMMENT '送餐员ID',
  `ORDER_ID` VARCHAR(40) NOT NULL COMMENT '订单ID',
  `PAY_AMOUNT` DECIMAL(10,4) NOT NULL COMMENT '收取金额',
  `OVER_STATUS` VARCHAR(2) NOT NULL COMMENT '订单收取完成状态00--客户未收取01---客户已收取',
  `CREATE_TIME` DATETIME NOT NULL COMMENT '创建时间',
  PRIMARY KEY (`DELIVERY_ORDER_BILL_ID`))
ENGINE = InnoDB
COMMENT = '商家送餐员订单收取金额表';


-- -----------------------------------------------------
-- Table `orderSystem`.`merchant_set_delivery_price`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `orderSystem`.`merchant_set_delivery_price` (
  `SET_DELIVERY_PRICE_ID` VARCHAR(40) NOT NULL COMMENT '设置送餐价格ID',
  `MERCHANT_ID` VARCHAR(40) NOT NULL COMMENT '商家ID',
  `DISTANCE` DECIMAL(5,1) NOT NULL COMMENT '距离',
  `PRICE` DECIMAL(10,4) NOT NULL COMMENT '价格',
  `LAST_UPDATE_TIME` DATETIME NOT NULL COMMENT '最后更新时间',
  PRIMARY KEY (`SET_DELIVERY_PRICE_ID`))
ENGINE = InnoDB
COMMENT = '商家设置送餐价格表';


-- -----------------------------------------------------
-- Table `orderSystem`.`merchant_set_delivery_price_history`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `orderSystem`.`merchant_set_delivery_price_history` (
  `SET_DELIVERY_PRICE_ID` VARCHAR(40) NOT NULL COMMENT '设置送餐价格ID',
  `MERCHANT_ID` VARCHAR(40) NOT NULL COMMENT '商家ID',
  `DISTANCE` DECIMAL(5,1) NOT NULL COMMENT '距离',
  `PRICE` DECIMAL(10,4) NOT NULL COMMENT '价格',
  `CREATE_DATE` DATETIME NOT NULL COMMENT '创建时间',
  PRIMARY KEY (`SET_DELIVERY_PRICE_ID`))
ENGINE = InnoDB
COMMENT = '商家设置送餐价格历史表';


-- -----------------------------------------------------
-- Table `orderSystem`.`user_permission`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `orderSystem`.`user_permission` (
  `USER_PERMISSION_ID` VARCHAR(40) NOT NULL COMMENT '用户类型角色ID',
  `USER_TYPE` VARCHAR(2) NOT NULL COMMENT '用户类型01--商家02---送餐员03---点餐客户',
  `PERMISSION_ID` VARCHAR(40) NOT NULL COMMENT '权限ID',
  `USER_PERMISSION_STATUS` VARCHAR(2) NOT NULL DEFAULT '01' COMMENT '用户类型角色状态00---无效01---有效',
  `CREATE_DATE` DATE NOT NULL COMMENT '创建日期',
  `LAST_UPDATE_DATE` DATE NOT NULL COMMENT '最后更新日期',
  PRIMARY KEY (`USER_PERMISSION_ID`))
ENGINE = InnoDB
COMMENT = '用户类型权限关系表';


-- -----------------------------------------------------
-- Table `orderSystem`.`permission`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `orderSystem`.`permission` (
  `PERMISSION_ID` VARCHAR(40) NOT NULL COMMENT '权限ID',
  `PERMISSION_NAME` VARCHAR(100) NOT NULL COMMENT '权限名称',
  `METHOD_NAME` VARCHAR(45) NOT NULL COMMENT '方法名称',
  `CREATE_DATE` DATE NOT NULL COMMENT '创建日期',
  PRIMARY KEY (`PERMISSION_ID`),
  UNIQUE INDEX `METHOD_NAME_UNIQUE` (`METHOD_NAME` ASC))
ENGINE = InnoDB
COMMENT = '权限表';


-- -----------------------------------------------------
-- Table `orderSystem`.`operation_log`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `orderSystem`.`operation_log` (
  `OPERATION_ID` VARCHAR(40) NOT NULL COMMENT '操作日志ID',
  `OPERATION_TYPE` VARCHAR(2) NOT NULL COMMENT '操作类型01---注册商家02---注册送餐员03---注册点餐用户04---用户点餐05---用户取消点餐06---商家接受点餐07---商家拒绝点餐08---送餐员接收订单09---送餐员送达订单10---用户确认订单11---订单扣款成功12---订单扣款失败13---商家新增产品14---商家删除产品15---商家恢复产品16---商家修改产品价格17----商家修改折扣信息18----商家新增送餐员单价19---商家修改送餐员单价20---用户评论商家21----用户给商家点赞',
  `FROM_ID` VARCHAR(40) NULL COMMENT '操作日志的来源对象ID',
  `TO_ID` VARCHAR(40) NULL COMMENT '操作日志的目的ID',
  `OPERATION_DESC` VARCHAR(200) NOT NULL COMMENT '操作描述',
  `CREATE_TIME` DATETIME NOT NULL COMMENT '创建时间',
  PRIMARY KEY (`OPERATION_ID`))
ENGINE = InnoDB
COMMENT = '操作日志';


-- -----------------------------------------------------
-- Table `orderSystem`.`merchant_public_discount`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `orderSystem`.`merchant_public_discount` (
  `MERCHANT_PUBLIC_ID` VARCHAR(40) NOT NULL COMMENT '商家公共折扣ID',
  `MERCHANT_ID` VARCHAR(40) NOT NULL COMMENT '商家ID',
  `PUBLIC_DISCOUNT_ID` VARCHAR(40) NOT NULL COMMENT '公共折扣ID',
  `LAST_UPDATE_TIME` DATETIME NOT NULL COMMENT '最后更新时间',
  PRIMARY KEY (`MERCHANT_PUBLIC_ID`))
ENGINE = InnoDB
COMMENT = '商家参加的公共折扣表';


-- -----------------------------------------------------
-- Table `orderSystem`.`public_discount_order_bill`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `orderSystem`.`public_discount_order_bill` (
  `PUBLIC_ORDER_BILL_ID` VARCHAR(40) NOT NULL COMMENT '订单公共折扣支付金额ID',
  `MERCHANT_ID` VARCHAR(40) NOT NULL COMMENT '商家ID',
  `ORDER_ID` VARCHAR(40) NOT NULL COMMENT '订单ID',
  `PUBLIC_DISCOUNT_ID` VARCHAR(40) NOT NULL COMMENT '公共折扣ID',
  `DISCOUNT_AMOUNT` DECIMAL(10,4) NOT NULL COMMENT '折扣金额',
  `OVER_STATUS` VARCHAR(2) NOT NULL COMMENT '订单收取完成状态00--客户未收取01---客户已收取',
  `CREATE_TIME` DATETIME NOT NULL COMMENT '创建时间',
  PRIMARY KEY (`PUBLIC_ORDER_BILL_ID`))
ENGINE = InnoDB
COMMENT = '订单的公共折扣支付金额表';


-- -----------------------------------------------------
-- Table `orderSystem`.`merchant_order_bill_temp`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `orderSystem`.`merchant_order_bill_temp` (
  `BILL_TEMP_ID` VARCHAR(40) NOT NULL COMMENT '未完成订单支付金额临时ID',
  `MERCHANT_ID` VARCHAR(40) NOT NULL COMMENT '商家ID',
  `ORDER_ID` VARCHAR(40) NOT NULL COMMENT '订单ID',
  `CLIENT_ID` VARCHAR(40) NOT NULL COMMENT '客户ID',
  `DELIVERY_ID` VARCHAR(40) NOT NULL COMMENT '送餐员ID',
  `PAY_SUM_AMOUNT` DECIMAL(10,4) NOT NULL COMMENT '支付金额',
  `CREATE_TIME` DATETIME NOT NULL COMMENT '创建时间',
  PRIMARY KEY (`BILL_TEMP_ID`))
ENGINE = InnoDB
COMMENT = '未完成订单的临时支付金额存储表';


-- -----------------------------------------------------
-- Table `orderSystem`.`merchant_public_discount_history`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `orderSystem`.`merchant_public_discount_history` (
  `MERCHANT_PUBLIC_ID` VARCHAR(40) NOT NULL COMMENT '商家公共折扣ID',
  `MERCHANT_ID` VARCHAR(40) NOT NULL COMMENT '商家ID',
  `PUBLIC_DISCOUNT_ID` VARCHAR(40) NOT NULL COMMENT '公共折扣ID',
  `CREATE_TIME` DATETIME NOT NULL COMMENT '创建时间',
  PRIMARY KEY (`MERCHANT_PUBLIC_ID`))
ENGINE = InnoDB
COMMENT = '商家参加的公共折扣历史表';


-- -----------------------------------------------------
-- Table `orderSystem`.`system_user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `orderSystem`.`system_user` (
  `SYSTEM_USER_ID` VARCHAR(40) NOT NULL COMMENT '系统用户管理员ID',
  `USER_LOGIN_NAME` VARCHAR(200) NOT NULL COMMENT '用户登陆名',
  `USER_NAME` VARCHAR(200) NOT NULL COMMENT '用户名',
  `USER_PASSWORD` VARCHAR(150) NOT NULL COMMENT '用户密码',
  `USER_TYPE` VARCHAR(2) NOT NULL COMMENT '用户类型04---超级管理员  05--12用户类型预留做管理员细分',
  `USER_PHONE` VARCHAR(20) NOT NULL COMMENT '管理员电话号码',
  `CREATE_DATE` DATE NOT NULL COMMENT '创建日期',
  `LAST_UPDATE_DATE` DATE NOT NULL COMMENT '最后修改日期',
  PRIMARY KEY (`SYSTEM_USER_ID`))
ENGINE = InnoDB
COMMENT = '系统管理员用户表';


-- -----------------------------------------------------
-- Table `orderSystem`.`product_price_history`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `orderSystem`.`product_price_history` (
  `PRODUCT_PRICE_HISTORY_ID` VARCHAR(40) NOT NULL COMMENT '产品价格历史表ID',
  `MERCHANT_ID` VARCHAR(40) NOT NULL COMMENT '商家ID',
  `MERCHANT_NAME` VARCHAR(200) NOT NULL COMMENT '商家名称',
  `PRODUCT_ID` VARCHAR(40) NOT NULL COMMENT '产品ID',
  `PRODUCT_NAME` VARCHAR(50) NOT NULL COMMENT '产品名称',
  `PRODUCT_PRICE` DECIMAL(10,4) NOT NULL COMMENT '产品历史价格',
  `CREATE_TIME` DATETIME NOT NULL COMMENT '创建时间',
  PRIMARY KEY (`PRODUCT_PRICE_HISTORY_ID`))
ENGINE = InnoDB
COMMENT = '产品价格历史表';


-- -----------------------------------------------------
-- Table `orderSystem`.`base_categories_data_info`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `orderSystem`.`base_categories_data_info` (
  `CATEGORIES_DATA_INFO_ID` VARCHAR(40) NOT NULL COMMENT '基础大类ID',
  `CATEGORIES_NAM` VARCHAR(45) NOT NULL COMMENT '大类名称',
  `CREATION_DATE` DATE NOT NULL COMMENT '创建日期',
  PRIMARY KEY (`CATEGORIES_DATA_INFO_ID`))
ENGINE = InnoDB
COMMENT = '基础信息大类';


-- -----------------------------------------------------
-- Table `orderSystem`.`base_sub_categories_data_info`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `orderSystem`.`base_sub_categories_data_info` (
  `SUB_CATEGORIES_DATA_INFO_ID` VARCHAR(40) NOT NULL COMMENT '基础小类ID',
  `CATEGORIES_DATA_INFO_ID` VARCHAR(40) NOT NULL COMMENT '基础大类ID',
  `CATEGORIES_CODE` VARCHAR(15) NOT NULL COMMENT '小类名称',
  `CATEGORIES_VALUE` VARCHAR(45) NOT NULL COMMENT '小类值',
  `CREATION_DATE` DATE NOT NULL COMMENT '创建时间',
  PRIMARY KEY (`SUB_CATEGORIES_DATA_INFO_ID`))
ENGINE = InnoDB
COMMENT = '基础信息小类';


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
