package com.yaya.orderApi.merchantModel;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

public class Merchant implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column merchant.MERCHANT_ID
     *
     * @mbg.generated
     */
    private String merchantId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column merchant.MERCHANT_LOGIN_NAME
     *
     * @mbg.generated
     */
    private String merchantLoginName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column merchant.MERCHANT_NAME
     *
     * @mbg.generated
     */
    private String merchantName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column merchant.MERCHANT_PASSWORD
     *
     * @mbg.generated
     */
    private String merchantPassword;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column merchant.SALT
     *
     * @mbg.generated
     */
    private String salt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column merchant.USER_TYPE
     *
     * @mbg.generated
     */
    private String userType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column merchant.MERCHANT_TEL_PHONE
     *
     * @mbg.generated
     */
    private String merchantTelPhone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column merchant.MERCHANT_MOBILEPHONE
     *
     * @mbg.generated
     */
    private String merchantMobilephone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column merchant.MERCHANT_BUSINESS_LICENSE
     *
     * @mbg.generated
     */
    private String merchantBusinessLicense;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column merchant.MERCHANT_PHOTO
     *
     * @mbg.generated
     */
    private String merchantPhoto;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column merchant.MERCHANT_ADDRESS
     *
     * @mbg.generated
     */
    private String merchantAddress;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column merchant.MERCHANT_LONGITUDE
     *
     * @mbg.generated
     */
    private BigDecimal merchantLongitude;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column merchant.MERCHANT_LATITUDE
     *
     * @mbg.generated
     */
    private BigDecimal merchantLatitude;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column merchant.MERCHANT_ENABLE
     *
     * @mbg.generated
     */
    private String merchantEnable;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column merchant.CREATE_TIME
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column merchant.LAST_UPDATE_TIME
     *
     * @mbg.generated
     */
    private Date lastUpdateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table merchant
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column merchant.MERCHANT_ID
     *
     * @return the value of merchant.MERCHANT_ID
     *
     * @mbg.generated
     */
    public String getMerchantId() {
        return merchantId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column merchant.MERCHANT_ID
     *
     * @param merchantId the value for merchant.MERCHANT_ID
     *
     * @mbg.generated
     */
    public void setMerchantId(String merchantId) {
        this.merchantId = merchantId == null ? null : merchantId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column merchant.MERCHANT_LOGIN_NAME
     *
     * @return the value of merchant.MERCHANT_LOGIN_NAME
     *
     * @mbg.generated
     */
    public String getMerchantLoginName() {
        return merchantLoginName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column merchant.MERCHANT_LOGIN_NAME
     *
     * @param merchantLoginName the value for merchant.MERCHANT_LOGIN_NAME
     *
     * @mbg.generated
     */
    public void setMerchantLoginName(String merchantLoginName) {
        this.merchantLoginName = merchantLoginName == null ? null : merchantLoginName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column merchant.MERCHANT_NAME
     *
     * @return the value of merchant.MERCHANT_NAME
     *
     * @mbg.generated
     */
    public String getMerchantName() {
        return merchantName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column merchant.MERCHANT_NAME
     *
     * @param merchantName the value for merchant.MERCHANT_NAME
     *
     * @mbg.generated
     */
    public void setMerchantName(String merchantName) {
        this.merchantName = merchantName == null ? null : merchantName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column merchant.MERCHANT_PASSWORD
     *
     * @return the value of merchant.MERCHANT_PASSWORD
     *
     * @mbg.generated
     */
    public String getMerchantPassword() {
        return merchantPassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column merchant.MERCHANT_PASSWORD
     *
     * @param merchantPassword the value for merchant.MERCHANT_PASSWORD
     *
     * @mbg.generated
     */
    public void setMerchantPassword(String merchantPassword) {
        this.merchantPassword = merchantPassword == null ? null : merchantPassword.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column merchant.SALT
     *
     * @return the value of merchant.SALT
     *
     * @mbg.generated
     */
    public String getSalt() {
        return salt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column merchant.SALT
     *
     * @param salt the value for merchant.SALT
     *
     * @mbg.generated
     */
    public void setSalt(String salt) {
        this.salt = salt == null ? null : salt.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column merchant.USER_TYPE
     *
     * @return the value of merchant.USER_TYPE
     *
     * @mbg.generated
     */
    public String getUserType() {
        return userType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column merchant.USER_TYPE
     *
     * @param userType the value for merchant.USER_TYPE
     *
     * @mbg.generated
     */
    public void setUserType(String userType) {
        this.userType = userType == null ? null : userType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column merchant.MERCHANT_TEL_PHONE
     *
     * @return the value of merchant.MERCHANT_TEL_PHONE
     *
     * @mbg.generated
     */
    public String getMerchantTelPhone() {
        return merchantTelPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column merchant.MERCHANT_TEL_PHONE
     *
     * @param merchantTelPhone the value for merchant.MERCHANT_TEL_PHONE
     *
     * @mbg.generated
     */
    public void setMerchantTelPhone(String merchantTelPhone) {
        this.merchantTelPhone = merchantTelPhone == null ? null : merchantTelPhone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column merchant.MERCHANT_MOBILEPHONE
     *
     * @return the value of merchant.MERCHANT_MOBILEPHONE
     *
     * @mbg.generated
     */
    public String getMerchantMobilephone() {
        return merchantMobilephone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column merchant.MERCHANT_MOBILEPHONE
     *
     * @param merchantMobilephone the value for merchant.MERCHANT_MOBILEPHONE
     *
     * @mbg.generated
     */
    public void setMerchantMobilephone(String merchantMobilephone) {
        this.merchantMobilephone = merchantMobilephone == null ? null : merchantMobilephone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column merchant.MERCHANT_BUSINESS_LICENSE
     *
     * @return the value of merchant.MERCHANT_BUSINESS_LICENSE
     *
     * @mbg.generated
     */
    public String getMerchantBusinessLicense() {
        return merchantBusinessLicense;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column merchant.MERCHANT_BUSINESS_LICENSE
     *
     * @param merchantBusinessLicense the value for merchant.MERCHANT_BUSINESS_LICENSE
     *
     * @mbg.generated
     */
    public void setMerchantBusinessLicense(String merchantBusinessLicense) {
        this.merchantBusinessLicense = merchantBusinessLicense == null ? null : merchantBusinessLicense.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column merchant.MERCHANT_PHOTO
     *
     * @return the value of merchant.MERCHANT_PHOTO
     *
     * @mbg.generated
     */
    public String getMerchantPhoto() {
        return merchantPhoto;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column merchant.MERCHANT_PHOTO
     *
     * @param merchantPhoto the value for merchant.MERCHANT_PHOTO
     *
     * @mbg.generated
     */
    public void setMerchantPhoto(String merchantPhoto) {
        this.merchantPhoto = merchantPhoto == null ? null : merchantPhoto.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column merchant.MERCHANT_ADDRESS
     *
     * @return the value of merchant.MERCHANT_ADDRESS
     *
     * @mbg.generated
     */
    public String getMerchantAddress() {
        return merchantAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column merchant.MERCHANT_ADDRESS
     *
     * @param merchantAddress the value for merchant.MERCHANT_ADDRESS
     *
     * @mbg.generated
     */
    public void setMerchantAddress(String merchantAddress) {
        this.merchantAddress = merchantAddress == null ? null : merchantAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column merchant.MERCHANT_LONGITUDE
     *
     * @return the value of merchant.MERCHANT_LONGITUDE
     *
     * @mbg.generated
     */
    public BigDecimal getMerchantLongitude() {
        return merchantLongitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column merchant.MERCHANT_LONGITUDE
     *
     * @param merchantLongitude the value for merchant.MERCHANT_LONGITUDE
     *
     * @mbg.generated
     */
    public void setMerchantLongitude(BigDecimal merchantLongitude) {
        this.merchantLongitude = merchantLongitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column merchant.MERCHANT_LATITUDE
     *
     * @return the value of merchant.MERCHANT_LATITUDE
     *
     * @mbg.generated
     */
    public BigDecimal getMerchantLatitude() {
        return merchantLatitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column merchant.MERCHANT_LATITUDE
     *
     * @param merchantLatitude the value for merchant.MERCHANT_LATITUDE
     *
     * @mbg.generated
     */
    public void setMerchantLatitude(BigDecimal merchantLatitude) {
        this.merchantLatitude = merchantLatitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column merchant.MERCHANT_ENABLE
     *
     * @return the value of merchant.MERCHANT_ENABLE
     *
     * @mbg.generated
     */
    public String getMerchantEnable() {
        return merchantEnable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column merchant.MERCHANT_ENABLE
     *
     * @param merchantEnable the value for merchant.MERCHANT_ENABLE
     *
     * @mbg.generated
     */
    public void setMerchantEnable(String merchantEnable) {
        this.merchantEnable = merchantEnable == null ? null : merchantEnable.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column merchant.CREATE_TIME
     *
     * @return the value of merchant.CREATE_TIME
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column merchant.CREATE_TIME
     *
     * @param createTime the value for merchant.CREATE_TIME
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column merchant.LAST_UPDATE_TIME
     *
     * @return the value of merchant.LAST_UPDATE_TIME
     *
     * @mbg.generated
     */
    public Date getLastUpdateTime() {
        return lastUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column merchant.LAST_UPDATE_TIME
     *
     * @param lastUpdateTime the value for merchant.LAST_UPDATE_TIME
     *
     * @mbg.generated
     */
    public void setLastUpdateTime(Date lastUpdateTime) {
        this.lastUpdateTime = lastUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table merchant
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", merchantId=").append(merchantId);
        sb.append(", merchantLoginName=").append(merchantLoginName);
        sb.append(", merchantName=").append(merchantName);
        sb.append(", merchantPassword=").append(merchantPassword);
        sb.append(", salt=").append(salt);
        sb.append(", userType=").append(userType);
        sb.append(", merchantTelPhone=").append(merchantTelPhone);
        sb.append(", merchantMobilephone=").append(merchantMobilephone);
        sb.append(", merchantBusinessLicense=").append(merchantBusinessLicense);
        sb.append(", merchantPhoto=").append(merchantPhoto);
        sb.append(", merchantAddress=").append(merchantAddress);
        sb.append(", merchantLongitude=").append(merchantLongitude);
        sb.append(", merchantLatitude=").append(merchantLatitude);
        sb.append(", merchantEnable=").append(merchantEnable);
        sb.append(", createTime=").append(createTime);
        sb.append(", lastUpdateTime=").append(lastUpdateTime);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}