package com.yaya.orderapi.merchantModel;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class MerchantExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table merchant
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table merchant
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table merchant
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table merchant
     *
     * @mbg.generated
     */
    public MerchantExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table merchant
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table merchant
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table merchant
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table merchant
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table merchant
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table merchant
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table merchant
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table merchant
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table merchant
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table merchant
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table merchant
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andMerchantIdIsNull() {
            addCriterion("MERCHANT_ID is null");
            return (Criteria) this;
        }

        public Criteria andMerchantIdIsNotNull() {
            addCriterion("MERCHANT_ID is not null");
            return (Criteria) this;
        }

        public Criteria andMerchantIdEqualTo(String value) {
            addCriterion("MERCHANT_ID =", value, "merchantId");
            return (Criteria) this;
        }

        public Criteria andMerchantIdNotEqualTo(String value) {
            addCriterion("MERCHANT_ID <>", value, "merchantId");
            return (Criteria) this;
        }

        public Criteria andMerchantIdGreaterThan(String value) {
            addCriterion("MERCHANT_ID >", value, "merchantId");
            return (Criteria) this;
        }

        public Criteria andMerchantIdGreaterThanOrEqualTo(String value) {
            addCriterion("MERCHANT_ID >=", value, "merchantId");
            return (Criteria) this;
        }

        public Criteria andMerchantIdLessThan(String value) {
            addCriterion("MERCHANT_ID <", value, "merchantId");
            return (Criteria) this;
        }

        public Criteria andMerchantIdLessThanOrEqualTo(String value) {
            addCriterion("MERCHANT_ID <=", value, "merchantId");
            return (Criteria) this;
        }

        public Criteria andMerchantIdLike(String value) {
            addCriterion("MERCHANT_ID like", value, "merchantId");
            return (Criteria) this;
        }

        public Criteria andMerchantIdNotLike(String value) {
            addCriterion("MERCHANT_ID not like", value, "merchantId");
            return (Criteria) this;
        }

        public Criteria andMerchantIdIn(List<String> values) {
            addCriterion("MERCHANT_ID in", values, "merchantId");
            return (Criteria) this;
        }

        public Criteria andMerchantIdNotIn(List<String> values) {
            addCriterion("MERCHANT_ID not in", values, "merchantId");
            return (Criteria) this;
        }

        public Criteria andMerchantIdBetween(String value1, String value2) {
            addCriterion("MERCHANT_ID between", value1, value2, "merchantId");
            return (Criteria) this;
        }

        public Criteria andMerchantIdNotBetween(String value1, String value2) {
            addCriterion("MERCHANT_ID not between", value1, value2, "merchantId");
            return (Criteria) this;
        }

        public Criteria andMerchantLoginNameIsNull() {
            addCriterion("MERCHANT_LOGIN_NAME is null");
            return (Criteria) this;
        }

        public Criteria andMerchantLoginNameIsNotNull() {
            addCriterion("MERCHANT_LOGIN_NAME is not null");
            return (Criteria) this;
        }

        public Criteria andMerchantLoginNameEqualTo(String value) {
            addCriterion("MERCHANT_LOGIN_NAME =", value, "merchantLoginName");
            return (Criteria) this;
        }

        public Criteria andMerchantLoginNameNotEqualTo(String value) {
            addCriterion("MERCHANT_LOGIN_NAME <>", value, "merchantLoginName");
            return (Criteria) this;
        }

        public Criteria andMerchantLoginNameGreaterThan(String value) {
            addCriterion("MERCHANT_LOGIN_NAME >", value, "merchantLoginName");
            return (Criteria) this;
        }

        public Criteria andMerchantLoginNameGreaterThanOrEqualTo(String value) {
            addCriterion("MERCHANT_LOGIN_NAME >=", value, "merchantLoginName");
            return (Criteria) this;
        }

        public Criteria andMerchantLoginNameLessThan(String value) {
            addCriterion("MERCHANT_LOGIN_NAME <", value, "merchantLoginName");
            return (Criteria) this;
        }

        public Criteria andMerchantLoginNameLessThanOrEqualTo(String value) {
            addCriterion("MERCHANT_LOGIN_NAME <=", value, "merchantLoginName");
            return (Criteria) this;
        }

        public Criteria andMerchantLoginNameLike(String value) {
            addCriterion("MERCHANT_LOGIN_NAME like", value, "merchantLoginName");
            return (Criteria) this;
        }

        public Criteria andMerchantLoginNameNotLike(String value) {
            addCriterion("MERCHANT_LOGIN_NAME not like", value, "merchantLoginName");
            return (Criteria) this;
        }

        public Criteria andMerchantLoginNameIn(List<String> values) {
            addCriterion("MERCHANT_LOGIN_NAME in", values, "merchantLoginName");
            return (Criteria) this;
        }

        public Criteria andMerchantLoginNameNotIn(List<String> values) {
            addCriterion("MERCHANT_LOGIN_NAME not in", values, "merchantLoginName");
            return (Criteria) this;
        }

        public Criteria andMerchantLoginNameBetween(String value1, String value2) {
            addCriterion("MERCHANT_LOGIN_NAME between", value1, value2, "merchantLoginName");
            return (Criteria) this;
        }

        public Criteria andMerchantLoginNameNotBetween(String value1, String value2) {
            addCriterion("MERCHANT_LOGIN_NAME not between", value1, value2, "merchantLoginName");
            return (Criteria) this;
        }

        public Criteria andMerchantNameIsNull() {
            addCriterion("MERCHANT_NAME is null");
            return (Criteria) this;
        }

        public Criteria andMerchantNameIsNotNull() {
            addCriterion("MERCHANT_NAME is not null");
            return (Criteria) this;
        }

        public Criteria andMerchantNameEqualTo(String value) {
            addCriterion("MERCHANT_NAME =", value, "merchantName");
            return (Criteria) this;
        }

        public Criteria andMerchantNameNotEqualTo(String value) {
            addCriterion("MERCHANT_NAME <>", value, "merchantName");
            return (Criteria) this;
        }

        public Criteria andMerchantNameGreaterThan(String value) {
            addCriterion("MERCHANT_NAME >", value, "merchantName");
            return (Criteria) this;
        }

        public Criteria andMerchantNameGreaterThanOrEqualTo(String value) {
            addCriterion("MERCHANT_NAME >=", value, "merchantName");
            return (Criteria) this;
        }

        public Criteria andMerchantNameLessThan(String value) {
            addCriterion("MERCHANT_NAME <", value, "merchantName");
            return (Criteria) this;
        }

        public Criteria andMerchantNameLessThanOrEqualTo(String value) {
            addCriterion("MERCHANT_NAME <=", value, "merchantName");
            return (Criteria) this;
        }

        public Criteria andMerchantNameLike(String value) {
            addCriterion("MERCHANT_NAME like", value, "merchantName");
            return (Criteria) this;
        }

        public Criteria andMerchantNameNotLike(String value) {
            addCriterion("MERCHANT_NAME not like", value, "merchantName");
            return (Criteria) this;
        }

        public Criteria andMerchantNameIn(List<String> values) {
            addCriterion("MERCHANT_NAME in", values, "merchantName");
            return (Criteria) this;
        }

        public Criteria andMerchantNameNotIn(List<String> values) {
            addCriterion("MERCHANT_NAME not in", values, "merchantName");
            return (Criteria) this;
        }

        public Criteria andMerchantNameBetween(String value1, String value2) {
            addCriterion("MERCHANT_NAME between", value1, value2, "merchantName");
            return (Criteria) this;
        }

        public Criteria andMerchantNameNotBetween(String value1, String value2) {
            addCriterion("MERCHANT_NAME not between", value1, value2, "merchantName");
            return (Criteria) this;
        }

        public Criteria andMerchantPasswordIsNull() {
            addCriterion("MERCHANT_PASSWORD is null");
            return (Criteria) this;
        }

        public Criteria andMerchantPasswordIsNotNull() {
            addCriterion("MERCHANT_PASSWORD is not null");
            return (Criteria) this;
        }

        public Criteria andMerchantPasswordEqualTo(String value) {
            addCriterion("MERCHANT_PASSWORD =", value, "merchantPassword");
            return (Criteria) this;
        }

        public Criteria andMerchantPasswordNotEqualTo(String value) {
            addCriterion("MERCHANT_PASSWORD <>", value, "merchantPassword");
            return (Criteria) this;
        }

        public Criteria andMerchantPasswordGreaterThan(String value) {
            addCriterion("MERCHANT_PASSWORD >", value, "merchantPassword");
            return (Criteria) this;
        }

        public Criteria andMerchantPasswordGreaterThanOrEqualTo(String value) {
            addCriterion("MERCHANT_PASSWORD >=", value, "merchantPassword");
            return (Criteria) this;
        }

        public Criteria andMerchantPasswordLessThan(String value) {
            addCriterion("MERCHANT_PASSWORD <", value, "merchantPassword");
            return (Criteria) this;
        }

        public Criteria andMerchantPasswordLessThanOrEqualTo(String value) {
            addCriterion("MERCHANT_PASSWORD <=", value, "merchantPassword");
            return (Criteria) this;
        }

        public Criteria andMerchantPasswordLike(String value) {
            addCriterion("MERCHANT_PASSWORD like", value, "merchantPassword");
            return (Criteria) this;
        }

        public Criteria andMerchantPasswordNotLike(String value) {
            addCriterion("MERCHANT_PASSWORD not like", value, "merchantPassword");
            return (Criteria) this;
        }

        public Criteria andMerchantPasswordIn(List<String> values) {
            addCriterion("MERCHANT_PASSWORD in", values, "merchantPassword");
            return (Criteria) this;
        }

        public Criteria andMerchantPasswordNotIn(List<String> values) {
            addCriterion("MERCHANT_PASSWORD not in", values, "merchantPassword");
            return (Criteria) this;
        }

        public Criteria andMerchantPasswordBetween(String value1, String value2) {
            addCriterion("MERCHANT_PASSWORD between", value1, value2, "merchantPassword");
            return (Criteria) this;
        }

        public Criteria andMerchantPasswordNotBetween(String value1, String value2) {
            addCriterion("MERCHANT_PASSWORD not between", value1, value2, "merchantPassword");
            return (Criteria) this;
        }

        public Criteria andSaltIsNull() {
            addCriterion("SALT is null");
            return (Criteria) this;
        }

        public Criteria andSaltIsNotNull() {
            addCriterion("SALT is not null");
            return (Criteria) this;
        }

        public Criteria andSaltEqualTo(String value) {
            addCriterion("SALT =", value, "salt");
            return (Criteria) this;
        }

        public Criteria andSaltNotEqualTo(String value) {
            addCriterion("SALT <>", value, "salt");
            return (Criteria) this;
        }

        public Criteria andSaltGreaterThan(String value) {
            addCriterion("SALT >", value, "salt");
            return (Criteria) this;
        }

        public Criteria andSaltGreaterThanOrEqualTo(String value) {
            addCriterion("SALT >=", value, "salt");
            return (Criteria) this;
        }

        public Criteria andSaltLessThan(String value) {
            addCriterion("SALT <", value, "salt");
            return (Criteria) this;
        }

        public Criteria andSaltLessThanOrEqualTo(String value) {
            addCriterion("SALT <=", value, "salt");
            return (Criteria) this;
        }

        public Criteria andSaltLike(String value) {
            addCriterion("SALT like", value, "salt");
            return (Criteria) this;
        }

        public Criteria andSaltNotLike(String value) {
            addCriterion("SALT not like", value, "salt");
            return (Criteria) this;
        }

        public Criteria andSaltIn(List<String> values) {
            addCriterion("SALT in", values, "salt");
            return (Criteria) this;
        }

        public Criteria andSaltNotIn(List<String> values) {
            addCriterion("SALT not in", values, "salt");
            return (Criteria) this;
        }

        public Criteria andSaltBetween(String value1, String value2) {
            addCriterion("SALT between", value1, value2, "salt");
            return (Criteria) this;
        }

        public Criteria andSaltNotBetween(String value1, String value2) {
            addCriterion("SALT not between", value1, value2, "salt");
            return (Criteria) this;
        }

        public Criteria andUserTypeIsNull() {
            addCriterion("USER_TYPE is null");
            return (Criteria) this;
        }

        public Criteria andUserTypeIsNotNull() {
            addCriterion("USER_TYPE is not null");
            return (Criteria) this;
        }

        public Criteria andUserTypeEqualTo(String value) {
            addCriterion("USER_TYPE =", value, "userType");
            return (Criteria) this;
        }

        public Criteria andUserTypeNotEqualTo(String value) {
            addCriterion("USER_TYPE <>", value, "userType");
            return (Criteria) this;
        }

        public Criteria andUserTypeGreaterThan(String value) {
            addCriterion("USER_TYPE >", value, "userType");
            return (Criteria) this;
        }

        public Criteria andUserTypeGreaterThanOrEqualTo(String value) {
            addCriterion("USER_TYPE >=", value, "userType");
            return (Criteria) this;
        }

        public Criteria andUserTypeLessThan(String value) {
            addCriterion("USER_TYPE <", value, "userType");
            return (Criteria) this;
        }

        public Criteria andUserTypeLessThanOrEqualTo(String value) {
            addCriterion("USER_TYPE <=", value, "userType");
            return (Criteria) this;
        }

        public Criteria andUserTypeLike(String value) {
            addCriterion("USER_TYPE like", value, "userType");
            return (Criteria) this;
        }

        public Criteria andUserTypeNotLike(String value) {
            addCriterion("USER_TYPE not like", value, "userType");
            return (Criteria) this;
        }

        public Criteria andUserTypeIn(List<String> values) {
            addCriterion("USER_TYPE in", values, "userType");
            return (Criteria) this;
        }

        public Criteria andUserTypeNotIn(List<String> values) {
            addCriterion("USER_TYPE not in", values, "userType");
            return (Criteria) this;
        }

        public Criteria andUserTypeBetween(String value1, String value2) {
            addCriterion("USER_TYPE between", value1, value2, "userType");
            return (Criteria) this;
        }

        public Criteria andUserTypeNotBetween(String value1, String value2) {
            addCriterion("USER_TYPE not between", value1, value2, "userType");
            return (Criteria) this;
        }

        public Criteria andMerchantTelPhoneIsNull() {
            addCriterion("MERCHANT_TEL_PHONE is null");
            return (Criteria) this;
        }

        public Criteria andMerchantTelPhoneIsNotNull() {
            addCriterion("MERCHANT_TEL_PHONE is not null");
            return (Criteria) this;
        }

        public Criteria andMerchantTelPhoneEqualTo(String value) {
            addCriterion("MERCHANT_TEL_PHONE =", value, "merchantTelPhone");
            return (Criteria) this;
        }

        public Criteria andMerchantTelPhoneNotEqualTo(String value) {
            addCriterion("MERCHANT_TEL_PHONE <>", value, "merchantTelPhone");
            return (Criteria) this;
        }

        public Criteria andMerchantTelPhoneGreaterThan(String value) {
            addCriterion("MERCHANT_TEL_PHONE >", value, "merchantTelPhone");
            return (Criteria) this;
        }

        public Criteria andMerchantTelPhoneGreaterThanOrEqualTo(String value) {
            addCriterion("MERCHANT_TEL_PHONE >=", value, "merchantTelPhone");
            return (Criteria) this;
        }

        public Criteria andMerchantTelPhoneLessThan(String value) {
            addCriterion("MERCHANT_TEL_PHONE <", value, "merchantTelPhone");
            return (Criteria) this;
        }

        public Criteria andMerchantTelPhoneLessThanOrEqualTo(String value) {
            addCriterion("MERCHANT_TEL_PHONE <=", value, "merchantTelPhone");
            return (Criteria) this;
        }

        public Criteria andMerchantTelPhoneLike(String value) {
            addCriterion("MERCHANT_TEL_PHONE like", value, "merchantTelPhone");
            return (Criteria) this;
        }

        public Criteria andMerchantTelPhoneNotLike(String value) {
            addCriterion("MERCHANT_TEL_PHONE not like", value, "merchantTelPhone");
            return (Criteria) this;
        }

        public Criteria andMerchantTelPhoneIn(List<String> values) {
            addCriterion("MERCHANT_TEL_PHONE in", values, "merchantTelPhone");
            return (Criteria) this;
        }

        public Criteria andMerchantTelPhoneNotIn(List<String> values) {
            addCriterion("MERCHANT_TEL_PHONE not in", values, "merchantTelPhone");
            return (Criteria) this;
        }

        public Criteria andMerchantTelPhoneBetween(String value1, String value2) {
            addCriterion("MERCHANT_TEL_PHONE between", value1, value2, "merchantTelPhone");
            return (Criteria) this;
        }

        public Criteria andMerchantTelPhoneNotBetween(String value1, String value2) {
            addCriterion("MERCHANT_TEL_PHONE not between", value1, value2, "merchantTelPhone");
            return (Criteria) this;
        }

        public Criteria andMerchantMobilephoneIsNull() {
            addCriterion("MERCHANT_MOBILEPHONE is null");
            return (Criteria) this;
        }

        public Criteria andMerchantMobilephoneIsNotNull() {
            addCriterion("MERCHANT_MOBILEPHONE is not null");
            return (Criteria) this;
        }

        public Criteria andMerchantMobilephoneEqualTo(String value) {
            addCriterion("MERCHANT_MOBILEPHONE =", value, "merchantMobilephone");
            return (Criteria) this;
        }

        public Criteria andMerchantMobilephoneNotEqualTo(String value) {
            addCriterion("MERCHANT_MOBILEPHONE <>", value, "merchantMobilephone");
            return (Criteria) this;
        }

        public Criteria andMerchantMobilephoneGreaterThan(String value) {
            addCriterion("MERCHANT_MOBILEPHONE >", value, "merchantMobilephone");
            return (Criteria) this;
        }

        public Criteria andMerchantMobilephoneGreaterThanOrEqualTo(String value) {
            addCriterion("MERCHANT_MOBILEPHONE >=", value, "merchantMobilephone");
            return (Criteria) this;
        }

        public Criteria andMerchantMobilephoneLessThan(String value) {
            addCriterion("MERCHANT_MOBILEPHONE <", value, "merchantMobilephone");
            return (Criteria) this;
        }

        public Criteria andMerchantMobilephoneLessThanOrEqualTo(String value) {
            addCriterion("MERCHANT_MOBILEPHONE <=", value, "merchantMobilephone");
            return (Criteria) this;
        }

        public Criteria andMerchantMobilephoneLike(String value) {
            addCriterion("MERCHANT_MOBILEPHONE like", value, "merchantMobilephone");
            return (Criteria) this;
        }

        public Criteria andMerchantMobilephoneNotLike(String value) {
            addCriterion("MERCHANT_MOBILEPHONE not like", value, "merchantMobilephone");
            return (Criteria) this;
        }

        public Criteria andMerchantMobilephoneIn(List<String> values) {
            addCriterion("MERCHANT_MOBILEPHONE in", values, "merchantMobilephone");
            return (Criteria) this;
        }

        public Criteria andMerchantMobilephoneNotIn(List<String> values) {
            addCriterion("MERCHANT_MOBILEPHONE not in", values, "merchantMobilephone");
            return (Criteria) this;
        }

        public Criteria andMerchantMobilephoneBetween(String value1, String value2) {
            addCriterion("MERCHANT_MOBILEPHONE between", value1, value2, "merchantMobilephone");
            return (Criteria) this;
        }

        public Criteria andMerchantMobilephoneNotBetween(String value1, String value2) {
            addCriterion("MERCHANT_MOBILEPHONE not between", value1, value2, "merchantMobilephone");
            return (Criteria) this;
        }

        public Criteria andMerchantBusinessLicenseIsNull() {
            addCriterion("MERCHANT_BUSINESS_LICENSE is null");
            return (Criteria) this;
        }

        public Criteria andMerchantBusinessLicenseIsNotNull() {
            addCriterion("MERCHANT_BUSINESS_LICENSE is not null");
            return (Criteria) this;
        }

        public Criteria andMerchantBusinessLicenseEqualTo(String value) {
            addCriterion("MERCHANT_BUSINESS_LICENSE =", value, "merchantBusinessLicense");
            return (Criteria) this;
        }

        public Criteria andMerchantBusinessLicenseNotEqualTo(String value) {
            addCriterion("MERCHANT_BUSINESS_LICENSE <>", value, "merchantBusinessLicense");
            return (Criteria) this;
        }

        public Criteria andMerchantBusinessLicenseGreaterThan(String value) {
            addCriterion("MERCHANT_BUSINESS_LICENSE >", value, "merchantBusinessLicense");
            return (Criteria) this;
        }

        public Criteria andMerchantBusinessLicenseGreaterThanOrEqualTo(String value) {
            addCriterion("MERCHANT_BUSINESS_LICENSE >=", value, "merchantBusinessLicense");
            return (Criteria) this;
        }

        public Criteria andMerchantBusinessLicenseLessThan(String value) {
            addCriterion("MERCHANT_BUSINESS_LICENSE <", value, "merchantBusinessLicense");
            return (Criteria) this;
        }

        public Criteria andMerchantBusinessLicenseLessThanOrEqualTo(String value) {
            addCriterion("MERCHANT_BUSINESS_LICENSE <=", value, "merchantBusinessLicense");
            return (Criteria) this;
        }

        public Criteria andMerchantBusinessLicenseLike(String value) {
            addCriterion("MERCHANT_BUSINESS_LICENSE like", value, "merchantBusinessLicense");
            return (Criteria) this;
        }

        public Criteria andMerchantBusinessLicenseNotLike(String value) {
            addCriterion("MERCHANT_BUSINESS_LICENSE not like", value, "merchantBusinessLicense");
            return (Criteria) this;
        }

        public Criteria andMerchantBusinessLicenseIn(List<String> values) {
            addCriterion("MERCHANT_BUSINESS_LICENSE in", values, "merchantBusinessLicense");
            return (Criteria) this;
        }

        public Criteria andMerchantBusinessLicenseNotIn(List<String> values) {
            addCriterion("MERCHANT_BUSINESS_LICENSE not in", values, "merchantBusinessLicense");
            return (Criteria) this;
        }

        public Criteria andMerchantBusinessLicenseBetween(String value1, String value2) {
            addCriterion("MERCHANT_BUSINESS_LICENSE between", value1, value2, "merchantBusinessLicense");
            return (Criteria) this;
        }

        public Criteria andMerchantBusinessLicenseNotBetween(String value1, String value2) {
            addCriterion("MERCHANT_BUSINESS_LICENSE not between", value1, value2, "merchantBusinessLicense");
            return (Criteria) this;
        }

        public Criteria andMerchantPhotoIsNull() {
            addCriterion("MERCHANT_PHOTO is null");
            return (Criteria) this;
        }

        public Criteria andMerchantPhotoIsNotNull() {
            addCriterion("MERCHANT_PHOTO is not null");
            return (Criteria) this;
        }

        public Criteria andMerchantPhotoEqualTo(String value) {
            addCriterion("MERCHANT_PHOTO =", value, "merchantPhoto");
            return (Criteria) this;
        }

        public Criteria andMerchantPhotoNotEqualTo(String value) {
            addCriterion("MERCHANT_PHOTO <>", value, "merchantPhoto");
            return (Criteria) this;
        }

        public Criteria andMerchantPhotoGreaterThan(String value) {
            addCriterion("MERCHANT_PHOTO >", value, "merchantPhoto");
            return (Criteria) this;
        }

        public Criteria andMerchantPhotoGreaterThanOrEqualTo(String value) {
            addCriterion("MERCHANT_PHOTO >=", value, "merchantPhoto");
            return (Criteria) this;
        }

        public Criteria andMerchantPhotoLessThan(String value) {
            addCriterion("MERCHANT_PHOTO <", value, "merchantPhoto");
            return (Criteria) this;
        }

        public Criteria andMerchantPhotoLessThanOrEqualTo(String value) {
            addCriterion("MERCHANT_PHOTO <=", value, "merchantPhoto");
            return (Criteria) this;
        }

        public Criteria andMerchantPhotoLike(String value) {
            addCriterion("MERCHANT_PHOTO like", value, "merchantPhoto");
            return (Criteria) this;
        }

        public Criteria andMerchantPhotoNotLike(String value) {
            addCriterion("MERCHANT_PHOTO not like", value, "merchantPhoto");
            return (Criteria) this;
        }

        public Criteria andMerchantPhotoIn(List<String> values) {
            addCriterion("MERCHANT_PHOTO in", values, "merchantPhoto");
            return (Criteria) this;
        }

        public Criteria andMerchantPhotoNotIn(List<String> values) {
            addCriterion("MERCHANT_PHOTO not in", values, "merchantPhoto");
            return (Criteria) this;
        }

        public Criteria andMerchantPhotoBetween(String value1, String value2) {
            addCriterion("MERCHANT_PHOTO between", value1, value2, "merchantPhoto");
            return (Criteria) this;
        }

        public Criteria andMerchantPhotoNotBetween(String value1, String value2) {
            addCriterion("MERCHANT_PHOTO not between", value1, value2, "merchantPhoto");
            return (Criteria) this;
        }

        public Criteria andMerchantAddressIsNull() {
            addCriterion("MERCHANT_ADDRESS is null");
            return (Criteria) this;
        }

        public Criteria andMerchantAddressIsNotNull() {
            addCriterion("MERCHANT_ADDRESS is not null");
            return (Criteria) this;
        }

        public Criteria andMerchantAddressEqualTo(String value) {
            addCriterion("MERCHANT_ADDRESS =", value, "merchantAddress");
            return (Criteria) this;
        }

        public Criteria andMerchantAddressNotEqualTo(String value) {
            addCriterion("MERCHANT_ADDRESS <>", value, "merchantAddress");
            return (Criteria) this;
        }

        public Criteria andMerchantAddressGreaterThan(String value) {
            addCriterion("MERCHANT_ADDRESS >", value, "merchantAddress");
            return (Criteria) this;
        }

        public Criteria andMerchantAddressGreaterThanOrEqualTo(String value) {
            addCriterion("MERCHANT_ADDRESS >=", value, "merchantAddress");
            return (Criteria) this;
        }

        public Criteria andMerchantAddressLessThan(String value) {
            addCriterion("MERCHANT_ADDRESS <", value, "merchantAddress");
            return (Criteria) this;
        }

        public Criteria andMerchantAddressLessThanOrEqualTo(String value) {
            addCriterion("MERCHANT_ADDRESS <=", value, "merchantAddress");
            return (Criteria) this;
        }

        public Criteria andMerchantAddressLike(String value) {
            addCriterion("MERCHANT_ADDRESS like", value, "merchantAddress");
            return (Criteria) this;
        }

        public Criteria andMerchantAddressNotLike(String value) {
            addCriterion("MERCHANT_ADDRESS not like", value, "merchantAddress");
            return (Criteria) this;
        }

        public Criteria andMerchantAddressIn(List<String> values) {
            addCriterion("MERCHANT_ADDRESS in", values, "merchantAddress");
            return (Criteria) this;
        }

        public Criteria andMerchantAddressNotIn(List<String> values) {
            addCriterion("MERCHANT_ADDRESS not in", values, "merchantAddress");
            return (Criteria) this;
        }

        public Criteria andMerchantAddressBetween(String value1, String value2) {
            addCriterion("MERCHANT_ADDRESS between", value1, value2, "merchantAddress");
            return (Criteria) this;
        }

        public Criteria andMerchantAddressNotBetween(String value1, String value2) {
            addCriterion("MERCHANT_ADDRESS not between", value1, value2, "merchantAddress");
            return (Criteria) this;
        }

        public Criteria andMerchantLongitudeIsNull() {
            addCriterion("MERCHANT_LONGITUDE is null");
            return (Criteria) this;
        }

        public Criteria andMerchantLongitudeIsNotNull() {
            addCriterion("MERCHANT_LONGITUDE is not null");
            return (Criteria) this;
        }

        public Criteria andMerchantLongitudeEqualTo(BigDecimal value) {
            addCriterion("MERCHANT_LONGITUDE =", value, "merchantLongitude");
            return (Criteria) this;
        }

        public Criteria andMerchantLongitudeNotEqualTo(BigDecimal value) {
            addCriterion("MERCHANT_LONGITUDE <>", value, "merchantLongitude");
            return (Criteria) this;
        }

        public Criteria andMerchantLongitudeGreaterThan(BigDecimal value) {
            addCriterion("MERCHANT_LONGITUDE >", value, "merchantLongitude");
            return (Criteria) this;
        }

        public Criteria andMerchantLongitudeGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("MERCHANT_LONGITUDE >=", value, "merchantLongitude");
            return (Criteria) this;
        }

        public Criteria andMerchantLongitudeLessThan(BigDecimal value) {
            addCriterion("MERCHANT_LONGITUDE <", value, "merchantLongitude");
            return (Criteria) this;
        }

        public Criteria andMerchantLongitudeLessThanOrEqualTo(BigDecimal value) {
            addCriterion("MERCHANT_LONGITUDE <=", value, "merchantLongitude");
            return (Criteria) this;
        }

        public Criteria andMerchantLongitudeIn(List<BigDecimal> values) {
            addCriterion("MERCHANT_LONGITUDE in", values, "merchantLongitude");
            return (Criteria) this;
        }

        public Criteria andMerchantLongitudeNotIn(List<BigDecimal> values) {
            addCriterion("MERCHANT_LONGITUDE not in", values, "merchantLongitude");
            return (Criteria) this;
        }

        public Criteria andMerchantLongitudeBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("MERCHANT_LONGITUDE between", value1, value2, "merchantLongitude");
            return (Criteria) this;
        }

        public Criteria andMerchantLongitudeNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("MERCHANT_LONGITUDE not between", value1, value2, "merchantLongitude");
            return (Criteria) this;
        }

        public Criteria andMerchantLatitudeIsNull() {
            addCriterion("MERCHANT_LATITUDE is null");
            return (Criteria) this;
        }

        public Criteria andMerchantLatitudeIsNotNull() {
            addCriterion("MERCHANT_LATITUDE is not null");
            return (Criteria) this;
        }

        public Criteria andMerchantLatitudeEqualTo(BigDecimal value) {
            addCriterion("MERCHANT_LATITUDE =", value, "merchantLatitude");
            return (Criteria) this;
        }

        public Criteria andMerchantLatitudeNotEqualTo(BigDecimal value) {
            addCriterion("MERCHANT_LATITUDE <>", value, "merchantLatitude");
            return (Criteria) this;
        }

        public Criteria andMerchantLatitudeGreaterThan(BigDecimal value) {
            addCriterion("MERCHANT_LATITUDE >", value, "merchantLatitude");
            return (Criteria) this;
        }

        public Criteria andMerchantLatitudeGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("MERCHANT_LATITUDE >=", value, "merchantLatitude");
            return (Criteria) this;
        }

        public Criteria andMerchantLatitudeLessThan(BigDecimal value) {
            addCriterion("MERCHANT_LATITUDE <", value, "merchantLatitude");
            return (Criteria) this;
        }

        public Criteria andMerchantLatitudeLessThanOrEqualTo(BigDecimal value) {
            addCriterion("MERCHANT_LATITUDE <=", value, "merchantLatitude");
            return (Criteria) this;
        }

        public Criteria andMerchantLatitudeIn(List<BigDecimal> values) {
            addCriterion("MERCHANT_LATITUDE in", values, "merchantLatitude");
            return (Criteria) this;
        }

        public Criteria andMerchantLatitudeNotIn(List<BigDecimal> values) {
            addCriterion("MERCHANT_LATITUDE not in", values, "merchantLatitude");
            return (Criteria) this;
        }

        public Criteria andMerchantLatitudeBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("MERCHANT_LATITUDE between", value1, value2, "merchantLatitude");
            return (Criteria) this;
        }

        public Criteria andMerchantLatitudeNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("MERCHANT_LATITUDE not between", value1, value2, "merchantLatitude");
            return (Criteria) this;
        }

        public Criteria andMerchantEnableIsNull() {
            addCriterion("MERCHANT_ENABLE is null");
            return (Criteria) this;
        }

        public Criteria andMerchantEnableIsNotNull() {
            addCriterion("MERCHANT_ENABLE is not null");
            return (Criteria) this;
        }

        public Criteria andMerchantEnableEqualTo(String value) {
            addCriterion("MERCHANT_ENABLE =", value, "merchantEnable");
            return (Criteria) this;
        }

        public Criteria andMerchantEnableNotEqualTo(String value) {
            addCriterion("MERCHANT_ENABLE <>", value, "merchantEnable");
            return (Criteria) this;
        }

        public Criteria andMerchantEnableGreaterThan(String value) {
            addCriterion("MERCHANT_ENABLE >", value, "merchantEnable");
            return (Criteria) this;
        }

        public Criteria andMerchantEnableGreaterThanOrEqualTo(String value) {
            addCriterion("MERCHANT_ENABLE >=", value, "merchantEnable");
            return (Criteria) this;
        }

        public Criteria andMerchantEnableLessThan(String value) {
            addCriterion("MERCHANT_ENABLE <", value, "merchantEnable");
            return (Criteria) this;
        }

        public Criteria andMerchantEnableLessThanOrEqualTo(String value) {
            addCriterion("MERCHANT_ENABLE <=", value, "merchantEnable");
            return (Criteria) this;
        }

        public Criteria andMerchantEnableLike(String value) {
            addCriterion("MERCHANT_ENABLE like", value, "merchantEnable");
            return (Criteria) this;
        }

        public Criteria andMerchantEnableNotLike(String value) {
            addCriterion("MERCHANT_ENABLE not like", value, "merchantEnable");
            return (Criteria) this;
        }

        public Criteria andMerchantEnableIn(List<String> values) {
            addCriterion("MERCHANT_ENABLE in", values, "merchantEnable");
            return (Criteria) this;
        }

        public Criteria andMerchantEnableNotIn(List<String> values) {
            addCriterion("MERCHANT_ENABLE not in", values, "merchantEnable");
            return (Criteria) this;
        }

        public Criteria andMerchantEnableBetween(String value1, String value2) {
            addCriterion("MERCHANT_ENABLE between", value1, value2, "merchantEnable");
            return (Criteria) this;
        }

        public Criteria andMerchantEnableNotBetween(String value1, String value2) {
            addCriterion("MERCHANT_ENABLE not between", value1, value2, "merchantEnable");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNull() {
            addCriterion("CREATE_TIME is null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNotNull() {
            addCriterion("CREATE_TIME is not null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeEqualTo(Date value) {
            addCriterion("CREATE_TIME =", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotEqualTo(Date value) {
            addCriterion("CREATE_TIME <>", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThan(Date value) {
            addCriterion("CREATE_TIME >", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("CREATE_TIME >=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThan(Date value) {
            addCriterion("CREATE_TIME <", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThanOrEqualTo(Date value) {
            addCriterion("CREATE_TIME <=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIn(List<Date> values) {
            addCriterion("CREATE_TIME in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotIn(List<Date> values) {
            addCriterion("CREATE_TIME not in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeBetween(Date value1, Date value2) {
            addCriterion("CREATE_TIME between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotBetween(Date value1, Date value2) {
            addCriterion("CREATE_TIME not between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andLastUpdateTimeIsNull() {
            addCriterion("LAST_UPDATE_TIME is null");
            return (Criteria) this;
        }

        public Criteria andLastUpdateTimeIsNotNull() {
            addCriterion("LAST_UPDATE_TIME is not null");
            return (Criteria) this;
        }

        public Criteria andLastUpdateTimeEqualTo(Date value) {
            addCriterion("LAST_UPDATE_TIME =", value, "lastUpdateTime");
            return (Criteria) this;
        }

        public Criteria andLastUpdateTimeNotEqualTo(Date value) {
            addCriterion("LAST_UPDATE_TIME <>", value, "lastUpdateTime");
            return (Criteria) this;
        }

        public Criteria andLastUpdateTimeGreaterThan(Date value) {
            addCriterion("LAST_UPDATE_TIME >", value, "lastUpdateTime");
            return (Criteria) this;
        }

        public Criteria andLastUpdateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("LAST_UPDATE_TIME >=", value, "lastUpdateTime");
            return (Criteria) this;
        }

        public Criteria andLastUpdateTimeLessThan(Date value) {
            addCriterion("LAST_UPDATE_TIME <", value, "lastUpdateTime");
            return (Criteria) this;
        }

        public Criteria andLastUpdateTimeLessThanOrEqualTo(Date value) {
            addCriterion("LAST_UPDATE_TIME <=", value, "lastUpdateTime");
            return (Criteria) this;
        }

        public Criteria andLastUpdateTimeIn(List<Date> values) {
            addCriterion("LAST_UPDATE_TIME in", values, "lastUpdateTime");
            return (Criteria) this;
        }

        public Criteria andLastUpdateTimeNotIn(List<Date> values) {
            addCriterion("LAST_UPDATE_TIME not in", values, "lastUpdateTime");
            return (Criteria) this;
        }

        public Criteria andLastUpdateTimeBetween(Date value1, Date value2) {
            addCriterion("LAST_UPDATE_TIME between", value1, value2, "lastUpdateTime");
            return (Criteria) this;
        }

        public Criteria andLastUpdateTimeNotBetween(Date value1, Date value2) {
            addCriterion("LAST_UPDATE_TIME not between", value1, value2, "lastUpdateTime");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table merchant
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table merchant
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}