package com.yaya.baseCategories.model;

import java.io.Serializable;
import java.util.Date;

public class BaseSubCategoriesDataInfo implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_sub_categories_data_info.SUB_CATEGORIES_DATA_INFO_ID
     *
     * @mbggenerated
     */
    private String subCategoriesDataInfoId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_sub_categories_data_info.CATEGORIES_DATA_INFO_ID
     *
     * @mbggenerated
     */
    private String categoriesDataInfoId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_sub_categories_data_info.CATEGORIES_CODE
     *
     * @mbggenerated
     */
    private String categoriesCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_sub_categories_data_info.CATEGORIES_VALUE
     *
     * @mbggenerated
     */
    private String categoriesValue;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_sub_categories_data_info.CREATION_DATE
     *
     * @mbggenerated
     */
    private Date creationDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table base_sub_categories_data_info
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_sub_categories_data_info.SUB_CATEGORIES_DATA_INFO_ID
     *
     * @return the value of base_sub_categories_data_info.SUB_CATEGORIES_DATA_INFO_ID
     *
     * @mbggenerated
     */
    public String getSubCategoriesDataInfoId() {
        return subCategoriesDataInfoId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_sub_categories_data_info.SUB_CATEGORIES_DATA_INFO_ID
     *
     * @param subCategoriesDataInfoId the value for base_sub_categories_data_info.SUB_CATEGORIES_DATA_INFO_ID
     *
     * @mbggenerated
     */
    public void setSubCategoriesDataInfoId(String subCategoriesDataInfoId) {
        this.subCategoriesDataInfoId = subCategoriesDataInfoId == null ? null : subCategoriesDataInfoId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_sub_categories_data_info.CATEGORIES_DATA_INFO_ID
     *
     * @return the value of base_sub_categories_data_info.CATEGORIES_DATA_INFO_ID
     *
     * @mbggenerated
     */
    public String getCategoriesDataInfoId() {
        return categoriesDataInfoId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_sub_categories_data_info.CATEGORIES_DATA_INFO_ID
     *
     * @param categoriesDataInfoId the value for base_sub_categories_data_info.CATEGORIES_DATA_INFO_ID
     *
     * @mbggenerated
     */
    public void setCategoriesDataInfoId(String categoriesDataInfoId) {
        this.categoriesDataInfoId = categoriesDataInfoId == null ? null : categoriesDataInfoId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_sub_categories_data_info.CATEGORIES_CODE
     *
     * @return the value of base_sub_categories_data_info.CATEGORIES_CODE
     *
     * @mbggenerated
     */
    public String getCategoriesCode() {
        return categoriesCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_sub_categories_data_info.CATEGORIES_CODE
     *
     * @param categoriesCode the value for base_sub_categories_data_info.CATEGORIES_CODE
     *
     * @mbggenerated
     */
    public void setCategoriesCode(String categoriesCode) {
        this.categoriesCode = categoriesCode == null ? null : categoriesCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_sub_categories_data_info.CATEGORIES_VALUE
     *
     * @return the value of base_sub_categories_data_info.CATEGORIES_VALUE
     *
     * @mbggenerated
     */
    public String getCategoriesValue() {
        return categoriesValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_sub_categories_data_info.CATEGORIES_VALUE
     *
     * @param categoriesValue the value for base_sub_categories_data_info.CATEGORIES_VALUE
     *
     * @mbggenerated
     */
    public void setCategoriesValue(String categoriesValue) {
        this.categoriesValue = categoriesValue == null ? null : categoriesValue.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_sub_categories_data_info.CREATION_DATE
     *
     * @return the value of base_sub_categories_data_info.CREATION_DATE
     *
     * @mbggenerated
     */
    public Date getCreationDate() {
        return creationDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_sub_categories_data_info.CREATION_DATE
     *
     * @param creationDate the value for base_sub_categories_data_info.CREATION_DATE
     *
     * @mbggenerated
     */
    public void setCreationDate(Date creationDate) {
        this.creationDate = creationDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_sub_categories_data_info
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", subCategoriesDataInfoId=").append(subCategoriesDataInfoId);
        sb.append(", categoriesDataInfoId=").append(categoriesDataInfoId);
        sb.append(", categoriesCode=").append(categoriesCode);
        sb.append(", categoriesValue=").append(categoriesValue);
        sb.append(", creationDate=").append(creationDate);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}