package com.yaya.merchant.dao;

import com.yaya.merchant.model.MerchantEvaluate;
import com.yaya.merchant.model.MerchantEvaluateExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface MerchantEvaluateMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table merchant_evaluate
     *
     * @mbg.generated
     */
    long countByExample(MerchantEvaluateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table merchant_evaluate
     *
     * @mbg.generated
     */
    int deleteByExample(MerchantEvaluateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table merchant_evaluate
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String merchantEvaluateId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table merchant_evaluate
     *
     * @mbg.generated
     */
    int insert(MerchantEvaluate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table merchant_evaluate
     *
     * @mbg.generated
     */
    int insertSelective(MerchantEvaluate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table merchant_evaluate
     *
     * @mbg.generated
     */
    List<MerchantEvaluate> selectByExample(MerchantEvaluateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table merchant_evaluate
     *
     * @mbg.generated
     */
    MerchantEvaluate selectByPrimaryKey(String merchantEvaluateId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table merchant_evaluate
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") MerchantEvaluate record, @Param("example") MerchantEvaluateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table merchant_evaluate
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") MerchantEvaluate record, @Param("example") MerchantEvaluateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table merchant_evaluate
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(MerchantEvaluate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table merchant_evaluate
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(MerchantEvaluate record);
}