package com.yaya.merchant.model;

import java.io.Serializable;

public class MerchantEvaluate implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column merchant_evaluate.MERCHANT_EVALUATE_ID
     *
     * @mbg.generated
     */
    private String merchantEvaluateId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column merchant_evaluate.EVALUATE_ID
     *
     * @mbg.generated
     */
    private String evaluateId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column merchant_evaluate.ORDER_ID
     *
     * @mbg.generated
     */
    private String orderId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column merchant_evaluate.USER_ID
     *
     * @mbg.generated
     */
    private String userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column merchant_evaluate.USER_TYPE
     *
     * @mbg.generated
     */
    private String userType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table merchant_evaluate
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column merchant_evaluate.MERCHANT_EVALUATE_ID
     *
     * @return the value of merchant_evaluate.MERCHANT_EVALUATE_ID
     *
     * @mbg.generated
     */
    public String getMerchantEvaluateId() {
        return merchantEvaluateId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column merchant_evaluate.MERCHANT_EVALUATE_ID
     *
     * @param merchantEvaluateId the value for merchant_evaluate.MERCHANT_EVALUATE_ID
     *
     * @mbg.generated
     */
    public void setMerchantEvaluateId(String merchantEvaluateId) {
        this.merchantEvaluateId = merchantEvaluateId == null ? null : merchantEvaluateId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column merchant_evaluate.EVALUATE_ID
     *
     * @return the value of merchant_evaluate.EVALUATE_ID
     *
     * @mbg.generated
     */
    public String getEvaluateId() {
        return evaluateId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column merchant_evaluate.EVALUATE_ID
     *
     * @param evaluateId the value for merchant_evaluate.EVALUATE_ID
     *
     * @mbg.generated
     */
    public void setEvaluateId(String evaluateId) {
        this.evaluateId = evaluateId == null ? null : evaluateId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column merchant_evaluate.ORDER_ID
     *
     * @return the value of merchant_evaluate.ORDER_ID
     *
     * @mbg.generated
     */
    public String getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column merchant_evaluate.ORDER_ID
     *
     * @param orderId the value for merchant_evaluate.ORDER_ID
     *
     * @mbg.generated
     */
    public void setOrderId(String orderId) {
        this.orderId = orderId == null ? null : orderId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column merchant_evaluate.USER_ID
     *
     * @return the value of merchant_evaluate.USER_ID
     *
     * @mbg.generated
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column merchant_evaluate.USER_ID
     *
     * @param userId the value for merchant_evaluate.USER_ID
     *
     * @mbg.generated
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column merchant_evaluate.USER_TYPE
     *
     * @return the value of merchant_evaluate.USER_TYPE
     *
     * @mbg.generated
     */
    public String getUserType() {
        return userType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column merchant_evaluate.USER_TYPE
     *
     * @param userType the value for merchant_evaluate.USER_TYPE
     *
     * @mbg.generated
     */
    public void setUserType(String userType) {
        this.userType = userType == null ? null : userType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table merchant_evaluate
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", merchantEvaluateId=").append(merchantEvaluateId);
        sb.append(", evaluateId=").append(evaluateId);
        sb.append(", orderId=").append(orderId);
        sb.append(", userId=").append(userId);
        sb.append(", userType=").append(userType);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}