

management:
  endpoints:
    web:
      exposure:
        include: '*'

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/orderSystem?serverTimezone=UTC&useUnicode=true&characterEncoding=UTF-8
    username: '{cipher}b69478cd62edfbc06be69aafb7933fb24367d3ee0c6667d2fd70484a60f64097'
    password: '{cipher}b69478cd62edfbc06be69aafb7933fb24367d3ee0c6667d2fd70484a60f64097'
    driver-class-name: com.mysql.jdbc.Driver
    tomcat:
      max-wait: 10000
      max-active: 5
      test-on-borrow: true
    hikari:
      #指定校验连接合法性执行的sql语句
      connection-test-query: select 1
      auto-commit: true
	  #注意的是这个地方的定义需要用在DataSourceConfig.java里面使用，是因为在定义JobEventConfig.java的时候需要引入自定义dataSource
    username: '{cipher}b69478cd62edfbc06be69aafb7933fb24367d3ee0c6667d2fd70484a60f64097'
    password: '{cipher}b69478cd62edfbc06be69aafb7933fb24367d3ee0c6667d2fd70484a60f64097'
    jdbc-url: jdbc:mysql://localhost:3306/orderSystem?serverTimezone=UTC&useUnicode=true&characterEncoding=UTF-8
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    publisher-confirms: true
    virtual-host: /
    listener:
      simple:
        acknowledge-mode: AUTO
  redis:
    #sentinel:
      # 这个名称一定与sentinel.conf文件中的sentinel monitor mymaster 172.168.1.3 6380 2名字相同
      #master: mymaster
      #nodes:
        #- 172.193.32.157:26389
        #- 172.193.32.158:26389
        #- 172.193.32.159:26389
    cluster:
      max-redirects: 3
      nodes:
        - 172.19.3.157:6359
        - 172.19.3.157:6360
        - 172.19.3.157:6361
        - 172.19.3.157:6362
        - 172.19.3.158:6359
        - 172.19.3.158:6360
        - 172.19.3.159:6359
        - 172.19.3.159:6360
    #host: 172.193.32.157
    #port: 6389
    lettuce:
      pool:
        max-idle: 8
        min-idle: 0
        max-active: 8
        max-wait: -1
    timeout: 5000
    database: 0
    #单位秒
    keytimeout: 1000

feign:
  compression:
    request:
      #开启请求压缩功能
      enabled: true
      #指定压缩请求数据类型
      mime-types: text/xml;application/xml;application/json
      #如果传输超过该字节，就对其进行压缩
      min-request-size: 2048
    #开启响应压缩功能
    response:
      enabled: true

mybatis:
  mapper-locations: classpath:mappers/*.xml
  config-location: classpath:page-config.xml


#配置log日志,可改成logging.level.root=DEBUG 更为详细的日志
logging:
  level:
    com:
      yaya: DEBUG
  path: /logs/
  
#redis cluster 集群定时刷新的间隔时间
redis:
  cluster:
    refresh:
      scheduled: 0/5 * * * * ?